### ISSUE TITLE
Latest version issues

### ISSUE THREAD

**Issue by kodi-lover** [123Venom/plugin.video.venom#101]
Since I updated to latest version this morning, it has broken the addon for me.

So every menu inside the discover TV shows no longer works, if I click on new TV shows (imdb) for example, I keep getting a check log error. This should be easy to reproduce without a log, just wondering if it is just me as was working fine before the latest update.

**Comment by knobby888** [comment]
I am also having the same problem

**Comment by GodsLikelyMe** [comment]
@knobby888 @kodi-lover  I had the same issue, but fixed it by uninstalling Venom and then reinstalling it. 

If that still doesn't work, try grabbing some logs for the dev.

**Comment by kodi-lover** [comment]
Fixed, now closing.

**Comment by 123Venom** [comment]
I'm guessing all that was needed to be done was a cache and metacache clear, your re-install was just the long unnecessary road to achieve the same thing.  That version the service was suppose to handle clearing both but it would not shock me if some devices failed to perform that automatically.  I know if those items are not cleared that will throw an error as the new Trakt Management Tools I added required meta changes to the db....hence the error thrown if not cleared.
