### ISSUE TITLE
Error on 90% of Menus

### ISSUE THREAD

**Issue by tempus2016** [123Venom/plugin.video.venom#102]
After the update, and the update to fox the broken update, i still have the same issue. 90% of menus dont work and it throws an error. Attached photos. 

I have cleared all cache, restarted kodi and uninstalled/reinstalled and still the same problem. Nvidia shield pro 2019, kodi 19. 
![image](https://user-images.githubusercontent.com/40920327/126080241-5ba2051b-aef9-4fa9-815d-8f3bef827af4.jpg)
![image](https://user-images.githubusercontent.com/40920327/126080250-1f2059d7-c938-40d0-abcb-c8972b8aca50.jpg)
![image](https://user-images.githubusercontent.com/40920327/126080258-3c2f8eb4-7f23-42a2-a489-b3f1c6f1d288.jpg)
![image](https://user-images.githubusercontent.com/40920327/126080267-7d3f39bc-6b3a-4657-abfe-13a55f315d03.jpg)

**Comment by shichen35** [comment]
I'm getting the same error

**Comment by tempus2016** [comment]
After hours looking for the issue, i fixed it. 

The dependecy script.skin.info.service was orphaned and on an old version. I updated the script, cleared cache and rebooted kodi and everything works again

**Comment by drinfernoo** [comment]
@tempus2016 Venom does not depend on anything called that... You're probably thinking of Skin Helper Service (`script.skin.helper.service`), but it doesn't depend on that either 😅

**Comment by mazzarito** [comment]
getting the same error so its not just him, as are a lot of others on reddit: https://www.reddit.com/r/Addons4Kodi/comments/omcu59/venom_stopped_working/

**Comment by tempus2016** [comment]
> @tempus2016 Venom does not depend on anything called that... You're probably thinking of Skin Helper Service (`script.skin.helper.service`), but it doesn't depend on that either 😅

I know it doesnt depend on either. I was stating what my issue was and how I fixed my issue. And no, I wasn’t thinking of Skin Helper. Look in my photos and you’ll see it’s not.

**Comment by drinfernoo** [comment]
@tempus2016 Your screenshots don't mention it either 🤔

Maybe you'd do best to share an actual log?

**Comment by drinfernoo** [comment]
@mazzarito One user in that thread linked to #101, in which @123Venom himself mentioned that clearing the add-on's cache might help... but nobody has been able to furnish a good error log to show what's actually happening 🤷🏼‍♀️

**Comment by tempus2016** [comment]
> @tempus2016 Your screenshots don't mention it either 🤔
> 
> Maybe you'd do best to share an actual log?

The very first error in the first screenshot shows the error. Why is it hard to see? 


![](https://user-images.githubusercontent.com/40920327/126080241-5ba2051b-aef9-4fa9-815d-8f3bef827af4.jpg)

**Comment by drinfernoo** [comment]
@tempus2016 Ah, somehow I missed that... Though, judging by the screenshots, it doesn't appear that is related to this Venom error. It happens before "Python engine initializing", which happens just before Venom is run, and the error occurs.

Again, an actual log is best for diagnosing issues.

**Comment by tempus2016** [comment]
> @tempus2016 Ah, somehow I missed that... Though, judging by the screenshots, it doesn't appear that is related to this Venom error. It happens before "Initializing Python engine", which happens just before Venom is run, and the error occurs.
> 
> Again, an actual log is best for diagnosing issues.

I’ve no idea why it worked but what I said above is the only thing that worked for me to get Venom to work. Updating the dependency, clearing cache and restarting kodi is the only thing that worked.

**Comment by drinfernoo** [comment]
@tempus2016 And according to the dev in #101, clearing the cache is the fix... so that's probably all you actually needed.

**Comment by tempus2016** [comment]
> @tempus2016 And according to the dev in #101, clearing the cache is the fix... so that's probably all you actually needed.

I lost count how many times I cleared the cache. I also reinstalled 4 times so clearing cache was not the fox for me.

**Comment by 123Venom** [comment]
> After the update, and the update to fox the broken update

Next time you post a smart ass remark like that you'll be blocked from here!  Not up for debate.

Update v6.0.7 had zero mentions of a fix for previous version so you're wrong there pal.  3 new features were added and a 4th item in the changelog mentions a cache clearing being required that some devices did not seem to accomplish, yet 3 ppl reverted for me to test and we could not duplicate the issue at all, in fact 20+ users in my keybase channel and nobody has reported having this issue so it's some edge case not all effected by.

Next time an error occurs post a log, both kodi.log and venom.log, with Venom set to **Debug** and **Logging Location** set to venom.log.
I'm wondering if you were clearing only cache and not both cache and **metacache**?  The problem surfaced due to the new meta added to db for the new **Trakt Management Tools** and **metacache** needs to rebuild from scratch.
