### ISSUE TITLE
Clearlogo doesn't work again, and now nowhere.  Can't see it anywhere... can that be true?

### ISSUE THREAD

**Issue by djdirty60** [123Venom/plugin.video.venom#107]
Clearlogo doesn't work again, and now nowhere.  Can't see it anywhere... can that be true?

_Originally posted by @djdirty60 in https://github.com/123Venom/plugin.video.venom/issues/99#issuecomment-887050618_

**Comment by drinfernoo** [comment]
Fanart.tv has been having issues today... it's likely that they're just not being able to be populated from the website.

That being said, everything's working fine on my end (Venom 6.0.9 and Arctic: Zephyr 2 - Resurrection 0.7.0) 😉 
![image](https://user-images.githubusercontent.com/2319508/127069760-79a744eb-9540-4b36-a974-30bec2eac2eb.png)

**Comment by djdirty60** [comment]
Auramod unfortunately nothing, new installation done.  Also nothing and not via the Skin you use

**Comment by drinfernoo** [comment]
Working fine for me in AuraMOD too 🤔

![screenshot00000](https://user-images.githubusercontent.com/2319508/127071338-34562b79-3ea1-43c3-a061-7cda663aaeb5.png)

For what it's worth, neither of the skins I've shown are the skin I "use", just two that came to mind that prominently show `clearlogo`. I actually prefer Arctic Horizon, which they are also working for.

![screenshot00001](https://user-images.githubusercontent.com/2319508/127071612-ec0e2832-21bf-40a8-ac6f-9e345835bba5.png)

What skin are you using that they aren't working with?

**Comment by djdirty60** [comment]
AuraMOD

**Comment by 123Venom** [comment]
fanart.tv let their ssl cert expire today and was down for a few hours.  It's best you learn to notice and check this stuff before I have to spend my time playing school teacher how to check this stuff.  Extended artwork from fanart.tv working fine here atm.

**Comment by djdirty60** [comment]
It's been like this for a few days

**Comment by drinfernoo** [comment]
@djdirty60 Then you're doing something wrong... It's obviously working.

**Comment by xyzfre** [comment]
I'm using AuraMod clear logos are working fine also on my end👍🏼￼

**Comment by djdirty60** [comment]
Fine, then it will be up to me

**Comment by drinfernoo** [comment]
Have you possibly looked in your log file to see if you're having errors connecting to Fanartv.tv? Have you disabled the artwork in Venom's settings?

There's clearly something happening that is on your end, as the add-on is successfully retrieving the artwork for other users.

**Comment by djdirty60** [comment]
Did a fresh install and didn't change the default settings of Venom.  Anders Addons will provide the artwork.  except venom

**Comment by drinfernoo** [comment]
Who's Anders?

**Comment by djdirty60** [comment]
Seren, theoath and fen.  only at fen there the streams no longer work

**Comment by 123Venom** [comment]
Provide a venom debug log and maybe we can see what's happening on your end that we're not experiencing.

**Comment by djdirty60** [comment]
http://paste.ubuntu.com/p/HmVFJNmDM7/

**Comment by 123Venom** [comment]
Nothing stands out in the kodi.log you provided that pertains to this.  I really need to see the Venom.log with it enabled to **Debugging** in settings.

**Comment by djdirty60** [comment]
#
[venom.log](https://github.com/123Venom/plugin.video.venom/files/6887971/venom.log)

**Comment by 123Venom** [comment]
I hoped for more data than that.  With what you provided there's not a single error to speak of in that tiny little log.  You have a few titles listed where fanart.tv does not have artwork for and this tells me the request is being made.  I do not log the successful requests as that would result in a bloated mess.  The first title in your log that states **NOT FOUND** is tmdb_id=768334 and this title is **A Classic Horror Story**

[https://fanart.tv/movie/768334/a-classic-horror-story/](https://fanart.tv/movie/768334/a-classic-horror-story/)

As you can see fanart.tv does not have artwork for that title so the log entry is correct and the request was made and returned the proper response.

  I'm sorry but this issue has not been duplicated by anyone thus far and there's got to be something wrong on your end.  I would suggest completely clearing cache and metacache.  Then browse around for longer than 6 minutes, and playing a video is not the best way to force fetching extended artwork from fanart.tv for logging purposes...browsing a large amount of titles is.

**Comment by 123Venom** [comment]
Here I completely cleared cache and metacache, which will force it to fetch fresh meta.  The discart image in this pic is only available via fanart.tv and that would not be present if there was a problem.

<img width="1109" alt="discart" src="https://user-images.githubusercontent.com/46383815/127214941-71bd8e3d-8cd0-455f-ba3f-5d88197c84f3.PNG">

**Comment by djdirty60** [comment]
Reinstalled everything from a clean kodi.  Log viewed doesn't show any error with downloading fanart, but still nothing visible...

![20210728_180346](https://user-images.githubusercontent.com/13561831/127357465-49f3eec2-977e-4e68-b08a-564eb8d1ed36.jpg)
![20210728_180410](https://user-images.githubusercontent.com/13561831/127357471-9f987464-2ac0-4f24-90ee-f9b41e724290.jpg)
![20210728_180426](https://user-images.githubusercontent.com/13561831/127357472-b03753d0-2c37-4e29-8cb3-65c69b0df3ab.jpg)

**Comment by 123Venom** [comment]
Why not just use Fen then?

**Comment by djdirty60** [comment]
Fixed issue after the update, thnx for the good work

**Comment by 123Venom** [comment]
> 
> 
> Fixed issue after the update, thnx for the good work

Once I spotted in your last few pics you were on a different lang I tested flipping my api lang and found the issue.  Problem came in that if no matching lang artwork was found my fallback only pulled `00`, `''` cases.  I needed to force pull any `en` lang also as a fallback. Generally that was fine for poster and fanart but clearart and clearlogo seldom ever have no lang associated with it as `00`, `''` like the other artwork does.

I'm going to prob make an issue template and your language in use should generally be an important thing you state up front.  That would have saved allot of trouble knowing off the bat.  I talk to allot of people daily and can not be expected to remember everyone's setup.

**Comment by djdirty60** [comment]
I understand that you can't remember everything, it works perfectly now thanks for the quick solution.

**Comment by 123Venom** [comment]
did you expect me to?

**Comment by djdirty60** [comment]
What do you mean?

**Comment by Arthur1967** [comment]
Thank you for all the work you do it’s working great for me I’m looking for
a show an older show and it brings it up but it says unavailable file is
that a setting or it’s just not available thank you

**Comment by 123Venom** [comment]
@Arthur1967  Why are you posting a new issue subject in a closed issue?  Also how can you expect I can check this when you provide such little to no detail?  What show?  So I have to make some assumptions here.....The time I can recall where I have anything state `unavailable file` is during the resolve process for a premium supported hoster and the debrid service responds back that the hoster file is `unavailable file` and I alert the user via a notification on screen.  If that's the case there's nothing I can do about that as the file has more than likely been removed by the hoster but the site returning said link has not been updated.  Providing a log is also beneficial.

**Comment by Arthur1967** [comment]
It’s working fine now since the latest update thank you

**Comment by 123Venom** [comment]
@djdirty60 Can you give me a few Dutch translations for strings I'm adding/changing.

1.) **"Enable Extended artwork (fanart.tv)"**
2.) **"Prefer TMDb artwork (poster, fanart, thumb)"**

**Comment by djdirty60** [comment]
> @djdirty60 Can you give me a few Dutch translations for strings I'm adding/changing.
> 
> 1.) **"Enable Extended artwork (fanart.tv)"**
> 2.) **"Prefer TMDb artwork (poster, fanart, thumb)"**

1.) **"Uitgebreide artwork inschakelen (fanart.tv)"**
2.) **"Voorkeur voor TMDb artwork (poster, fanart, thumb)"**

**Comment by 123Venom** [comment]
Thank you.  One new one

3.) **"Terminate on Cloud Sources"**

**Comment by djdirty60** [comment]
> Thank you. One new one
> 
> 3.) **"Terminate on Cloud Sources"**

3.) "Beëindigen op cloudbronnen"
