### ISSUE TITLE
very slow buffering compared to other addons

### ISSUE THREAD

**Issue by bloatworm2** [123Venom/plugin.video.venom#112]
Hi, 

Great addon thank you.

The buffering when watching shows or movies seems really poor compared to other addons. Is there anything I can do to sort that out as I prefer V addon. 

V19 and 6.1.5.

**Comment by drinfernoo** [comment]
This has absolutely nothing to do with Venom (or any other add-on). As soon as a file is playing, the add-on is no longer involved.

**Comment by Arthur1967** [comment]
I’m using the add-on right now and it’s working absolutely flawlessly Thank
you

**Comment by 123Venom** [comment]
closing due to not addon related issue.
