### ISSUE TITLE
Ver 6.1.7 problem with MY COLLECTION

### ISSUE THREAD

**Issue by jaimsitecom** [123Venom/plugin.video.venom#114]
Whenever i go to the folder ‘MY COLLECTION’, it will say it is empty. Then all options will be unclickable or will not work. I had to close venom addon for it to work again. As long as i dont go to COLLECTIONS, it will be working. I know this started in ver 6.1.6, but still exists in the latest version 6.1.7. 

I just had to downgrade back to 6.1.5, now everything is back to normal.

**Comment by 123Venom** [comment]
There is no gui menu labelled **"My Collection"**, there are three similar menus as follows...
1.) Discover Movies - Collections
2.) My Movies - Collections
3.) My TV Shows - Collections

Which one of those?  All three are loading fine here.  Please provide a venom debug log.

**Comment by jaimsitecom** [comment]
> There is no gui menu labelled **"My Collection"**, there are three similar menus as follows...
> 1.) Discover Movies - Collections
> 2.) My Movies - Collections
> 3.) My TV Shows - Collections
> 
> Which one of those? All three are loading fine here. Please provide a venom debug log.

Both ‘My Moies - Collection’ and ‘My Tv Shows - Collection’ came out empty in version 6.1.6 and 6.1.7. 

Had to go back to 6.1.5 to get back the functions for both folders. 

Ty!

**Comment by 123Venom** [comment]
I can not reproduce so without the debug log i asked you for it's a guessing game.

**Comment by jaimsitecom** [comment]
Ok i will update to 6.1.7 again and send the log. Thanks

**Comment by jaimsitecom** [comment]
No need. After re-updating to 6.1.7, a prompt popped up saying ‘venom forced clear trakt files’, now the ‘my tv shows- collection’ opens up and lists down the shows correctly whereas before it was empty. Phew. 

Sorry for this. I will close it now. Thanks so much.

**Comment by 123Venom** [comment]
np...glad ya got it sorted.
