### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by djdirty60** [123Venom/plugin.video.venom#117]
Good day,

Is it possible that there will be a function for automatic subtitles download and whether a4ksubtitles will be integrated so that it opens automatically when a subtitle is found?

 Would like to hear.

**Comment by 123Venom** [comment]
The a4ksubtitles addon should be working.  The built-in uses opensubtitles.org and should be working but I honestly do not use subtitles and have not touched a lick of that code in prob 2yrs.  I tested 3 titles and 2 were found on opensubtitles and seemed fine while one was not available.

**Comment by djdirty60** [comment]
Ow ok, with the Dutch language he unfortunately does not download it himself or does not appear a window itself.  It will probably only work under English language.

 But thanks for watching

**Comment by 123Venom** [comment]
I spent a bit more time on this.  The internal opensubtitles was actually NOT working as expected.  I should have been looking for the actual written subs file and when that occurs you should see ex. `Dutch - TemporarySubs (External)`.  The User Agent was old and needed to be updated.  This seems to cure it now and returns a valid token to make the request to fetch the desired subs, if available.  One thing to note with this fix...if Kodi reports the stream has the required subtitles it will not bother to download a local version also.  I added a notification pop up to alert you that the sub file was downloaded, you can turn this off in Subtitle settings if you find it annoying.

<img width="550" alt="150" src="https://user-images.githubusercontent.com/46383815/130666524-0c7fb28b-58e9-4cd8-ac70-90b719e2cb14.PNG">

<img width="978" alt="151" src="https://user-images.githubusercontent.com/46383815/130666546-7ac595b5-dff3-4f73-880c-95b16429bea9.PNG">

**Comment by djdirty60** [comment]
Thnx you are a hero

**Comment by 123Venom** [comment]
latest is pushed with that fix...let me know how that goes now with Dutch subs

**Comment by djdirty60** [comment]
It works perfectly, thnx for your work
