### ISSUE TITLE
TV Show Progress

### ISSUE THREAD

**Issue by naudski** [123Venom/plugin.video.venom#118]
Thanks again for the manual Trakt Sync option. Works great!
There is one other thing I noticed when I was watching a show today. I added it to my watchlist and stopped watching after 4 episodes. After this it was removed from my watchlist which is expected, but episode 5 did not appear in the Progress list. I cleared the cache and did a manual sync but that did not help.
Can you reproduce this?

**Comment by naudski** [comment]
Sorry, this is a non-issue. I found out the show was hidden from my Progress list, haha.

**Comment by 123Venom** [comment]
Progress Manager in the Trakt Management Tools is good for finding those.
