### ISSUE TITLE
Exclude bad cached pack using keyword

### ISSUE THREAD

**Issue by vagueink** [123Venom/plugin.video.venom#119]
Currently watching Community (Season 3) using All Debrid (also tested with real debrid). There is a cached pack torrent that is the top result and the pack is actually mis packed and has mislabeled the 3rd episode throwing the entire season off. The work around was caching another source but this second source always is 2nd in the source select and breaks the Up Next feature. 

The title of the pack is 

Community.S03.1080p.BlueRay.x264-YELLOWBiRD[rartv]

Since it is cached already adding the source to the undesirables list has no effect.

I was wondering if there would be a way to exclude bad torrents either from the contextual menu in the source select or by adding a keyword to the exclusion. In this case the keyword would be "YELLOWBiRD" or similar. The contextual menu would be easier as it could use the entire title as the string for exclusion.

Hope this reaches someone, and thank you for this amazing plugin.

**Comment by vagueink** [comment]
Ohh, I tried that but though the undesirables was only for scrapers and not usable for generic search strings. I should have just tried "yellowbird"...thanks for directing me. I will try that tonight.

It would be so cool if that could be integrated into the contextual menu as well.

Great job and thank you!

**Comment by 123Venom** [comment]
Sorry but we all chose to integrate it where it sits and works just fine and it does not seem an interest in changing the current method.

**Comment by vagueink** [comment]
No problem. It works great. Thanks for the help.
