### ISSUE TITLE
Trakt progress not showing any episodes.

### ISSUE THREAD

**Issue by rrosajp** [123Venom/plugin.video.venom#12]
@123Venom  hi
New Episods (Trakt)  or Progress in My TV show menu item not populating .

**Comment by SahibzadaAliNoor** [comment]
Having this issue since today

**Comment by 123Venom** [comment]
Ya i heard last night.  I got a typo in last update busted trakt lists when I added new actor profile pics. Gone for a week but ill try and see if i can take care of this later tonight

**Comment by SahibzadaAliNoor** [comment]
Cheers

Kind regards,
SAN

**Comment by SahibzadaAliNoor** [comment]
The issue still persists after the updating to v 3.1.6. Trakt doesn't seem to populate lists under MYTVSHOWS - PROGRESS or NEW EPISODES (Trakt). 

Rest of the Trakt features in TV shows and Movies work fine e.g TVSHOWS - TRENDING.

**Comment by 123Venom** [comment]
I just checked and both progress and new episodes(trakt) is now working fine here now.  Try clearing all cache..something from failed attempt might be stuck in the cache.  And make sure sidepanel option is on "all videos" and report back

**Comment by SahibzadaAliNoor** [comment]
Thank you too sir. That did the trick 😊

**Comment by 123Venom** [comment]
Closing this and sorry for the typo goof folks..never pays rushing something out.  I was leaving for vaca and should have just let it be till I got back
