### ISSUE TITLE
[BUG] Believe its a bug... Takes several tries to get Trakt to Authorize.

### ISSUE THREAD

**Issue by dreulavelle** [123Venom/plugin.video.venom#122]
To get Trakt to stick within Kodi, it takes a few times for it to finally accept it.. is this a bug or is there a specific way to auth for it to work the first time?

**Comment by 123Venom** [comment]
The only time I've seen it not stick is when you do not hit **OK** on both screens for **My Accounts** as well as **Venom**.

**Comment by dreulavelle** [comment]
Should we be authing from Venom or from My Accounts? Or does it matter

**Comment by 123Venom** [comment]
Venom has no means to Auth Trakt..what are you looking at?
