### ISSUE TITLE
Genre

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#125]
Hi,

I hope you're well.

This is more of an enhancement than anything else.

I use a few widgets on Auramod that I point directly at genre, then what I like,
Trending
Action
Adventure
Sci fi
Horror,

Now I am guessing the genre are collating info from track on trending in that genre? Is there a way to maybe have a function that It can be pointed at popular?

It's just a lot of the movies are duplicates. 

Does this make sense?

**Comment by 123Venom** [comment]
Genre titles actually come from an IMDb query.  I've never switched meta providers for that nor really care to.  Can you show me a screenshot of these duplicates.

**Comment by adamosborne83** [comment]
> Genre titles actually come from an IMDb query. I've never switched meta providers for that nor really care to. Can you show me a screenshot of these duplicates.

Please see below pics, now I know that it is all to do with how the films are tagged, but it does just seem that a majority of films are the same as trending.
I apologise for asking, as know this is a free and I am not ungrateful at all.

Trending 
![20210907_064653](https://user-images.githubusercontent.com/78307374/132300388-3a652f4b-3b86-4e11-9627-7b49bc586487.jpg)

Action
![20210907_064715](https://user-images.githubusercontent.com/78307374/132300461-d54ab37c-958a-4b39-9135-369d1ac30d14.jpg)

Adventure 
![20210907_064731](https://user-images.githubusercontent.com/78307374/132300537-24376200-4aeb-4301-9728-b26cc32faafe.jpg)


Fantasy
![20210907_064745](https://user-images.githubusercontent.com/78307374/132300597-f60aec3e-e66e-4fae-bc0a-d5e13d5c8c11.jpg)

Horror
![20210907_064801](https://user-images.githubusercontent.com/78307374/132300616-3baebacd-50a2-4b9a-95bd-0ee88f6823ef.jpg)

Sci-fi
![20210907_064816](https://user-images.githubusercontent.com/78307374/132300663-f8b507e9-d88f-4928-8945-d8de3dae92ac.jpg)

**Comment by 123Venom** [comment]
First Trending (Trakt) list should not be compared to Genre (IMDb) lists as they comes from different meta providers.  They have nothing to do with one another but if the lists contain similar titles so be it, many will.  Some of your Genre pics my lists did not match till I went a couple pages in...were you taking pics of random pages to show they are very similar?  You realize some of the tiles in your pics have 3-4 Genres lists so they're going to appear in those other categories as well.

You'll find the same similar condition in other addons.  Action, Adventure, Fantasy are pretty tied together allot of times and those lists will contain many of the same titles, that can't be changed..lol

Here's Seren's...and first pic is even Trakt Trending, which should NOT be compared.

<img width="834" alt="Seren_Trakt_trending" src="https://user-images.githubusercontent.com/46383815/132319896-c0f2170b-5ebb-4b28-b851-16cfd05c99d9.PNG">
<img width="864" alt="Seren_Action" src="https://user-images.githubusercontent.com/46383815/132319933-7bd2bc26-d681-4aeb-b9a5-d30d55250d3d.PNG">
<img width="842" alt="Seren_Adventure" src="https://user-images.githubusercontent.com/46383815/132319957-50a36a13-f235-47c9-8ae0-ddbf63ea07d2.PNG">

**Comment by adamosborne83** [comment]
> First Trending (Trakt) list should not be compared to Genre (IMDb) lists as they comes from different meta providers. They have nothing to do with one another but if the lists contain similar titles so be it, many will. Some of your Genre pics my lists did not match till I went a couple pages in...were you taking pics of random pages to show they are very similar? You realize some of the tiles in your pics have 3-4 Genres lists so they're going to appear in those other categories as well.
> 
> You'll find the same similar condition in other addons. Action, Adventure, Fantasy are pretty tied together allot of times and those lists will contain many of the same titles, that can't be changed..lol
> 
> Here's Seren's...and first pic is even Trakt Trending, which should NOT be compared.
> 
> <img alt="Seren_Trakt_trending" width="834" src="https://user-images.githubusercontent.com/46383815/132319896-c0f2170b-5ebb-4b28-b851-16cfd05c99d9.PNG">
> 
> <img alt="Seren_Action" width="864" src="https://user-images.githubusercontent.com/46383815/132319933-7bd2bc26-d681-4aeb-b9a5-d30d55250d3d.PNG">
> 
> <img alt="Seren_Adventure" width="842" src="https://user-images.githubusercontent.com/46383815/132319957-50a36a13-f235-47c9-8ae0-ddbf63ea07d2.PNG">

I totally get that, it's just an annoying thing that's all.
I do use seren for widgets as there is a setting to change it from Trending to Popular,

It's just I get bored of seeing the same films that's all, as I need inspiration to save hours of flicking. 

I am thinking of doing something with Autowidget which will stop the problem..... 

Just have it pointed at Next Page, so it then has a good 10 pages of each genre to then randomise for me. 

Thank you anyway for the info

**Comment by 123Venom** [comment]
Ya it can be annoying but there's not allot I can do about the genre classes assigned to films that can make it end up in 3-4 different Genre lists.  You do know that for both Movies and TV Shows I have an IMDb sort option in the settings right?  You could switch that up from time to time if you want and sort by title, rating, votes, date premiered.  Some skins have a Random sort already and I think Auto-Widgets takes this a little further.

**Comment by 123Venom** [comment]
I know why my lists look different that your pics.  I use date premiered and I believe you must be on the default option, which i believe sorts by rating. The flipped to date premiered.  They still contain similar titles but ordered a bit different.  Action and Adventure are tough genres...to many titles share it

**Comment by adamosborne83** [comment]
> I know why my lists look different that your pics. I use date premiered and I believe you must be on the default option, which i believe sorts by rating. The flipped to date premiered. They still contain similar titles but ordered a bit different. Action and Adventure are tough genres...to many titles share it

No no it's fine, I know I was asking for a bit too much, I do have it set to random on the widget through Auramod Skin, it's just the movies never change too much. 

Autowidget it is, I'll play at weekend. 

Thank you again for actually looking at this though.
