### ISSUE TITLE
Trakt liked lists 

### ISSUE THREAD

**Issue by djdirty60** [123Venom/plugin.video.venom#126]
Hello, 

Trakt's liked lists don't work via widgets in Titan bingie mod, indicates when loading it, nothing found.  Can you maybe look at that?

![1631391605506882058451903787383](https://user-images.githubusercontent.com/13561831/132960647-489160d2-f924-498f-88ad-ed5d44af045e.jpg)

**Comment by 123Venom** [comment]
try resetting the widget.  I recently moved the list so it had it's own `My Liked List` and that broken any prior wdiget references to it.

**Comment by djdirty60** [comment]
Is a fresh install, and it's hubs at Titan bingie mod.  Maybe it's that?

**Comment by 123Venom** [comment]
I've not tested that skin and honestly I've got to many as it is to get into yet another.  3 skins I did check I can not reproduce it
<img width="1149" alt="26a" src="https://user-images.githubusercontent.com/46383815/133113742-c97bc3d1-fbe9-4c1c-9dfe-02599236e501.PNG">
