### ISSUE TITLE
[Feature Request] Prioritize HDR 

### ISSUE THREAD

**Issue by rizreflects** [123Venom/plugin.video.venom#127]
Would you consider adding an option that lets you prioritize HDR links above everything else? Let's say for example there is a 20gb movie that is HDR, and there is another movie that is 25gb but SDR, venom will go with the SDR one because it's a larger file size. Do you think you could make it so if HDR is present, then those links will be prioritized above the SDR ones regardless of file size? 

Imo this would make autoplay perfect.. as searching for HDR links is the only reason I use source select.

**Comment by 123Venom** [comment]
I'll look into adding it when I get a chance.
