### ISSUE TITLE
Real Debrid doesn't work on Venom

### ISSUE THREAD

**Issue by Davidabbasi** [123Venom/plugin.video.venom#130]
So I need to reauthorize for some reason my real debrid account. I have an active premium account. So I reauthorized but for some reason still keep getting a message popping up saying that I need an account.

**Comment by Arthur1967** [comment]
I just checked mine and I have to renew my debrid acct to going to renew it and see if it sticks￼￼￼

**Comment by Arthur1967** [comment]
All I did was hit resynce my accounts￼ and enable whatever debrid account you have￼￼ And that works for me￼

**Comment by Davidabbasi** [comment]
It didn't work for me unfortunately. I refreshed my account and it was
authorized but it kept giving me the message that I needed at the Brit
account. So I just deleted Kodi since reinstalling Venom did not work. I'll
try doing a fresh install and see if that works.

**Comment by Arthur1967** [comment]
After you re-sync your account you have to go back into it and there's a toggle for rd to enable And turn that on￼￼ And you can set the priority there too￼

**Comment by 123Venom** [comment]
Once you auth in My Accounts make sure to hit OK in that addon and then you MUST hit OK in Venom also.  Not sure if that's the reason but every once in awhile I hear of this issue and can not reproduce it.  Try again and upload a venom.log and kodi.log file

**Comment by Davidabbasi** [comment]
Thank you. I went into tools and then settings for accounts and was able to
enable it like you said. It works now.
