### ISSUE TITLE
Venom scraping "None" for movies and shows via TMDB helper

### ISSUE THREAD

**Issue by Fubuz** [123Venom/plugin.video.venom#131]
I've got a weird problem for quite a while now while scraping with Venom, whenever that is local library .strm of tmdb helper or via the tmdb helper addon itself.

The scraping always show title as "None (None)", both for movies and tv shows. The end result is a wrong scrape or nothin is found.

I am attaching a picture and kodi log for you to hopefully indentify the problem. Thank you for your time!

![Capture](https://user-images.githubusercontent.com/69593507/135507645-06cfb614-36be-4d9d-97c0-cf2920ecfb64.JPG)

[kodi.log](https://github.com/123Venom/plugin.video.venom/files/7261587/kodi.log)

**Comment by 123Venom** [comment]
That's a weird issue..never seen that happen. That's titling info that should appear in that header and if it's not available the scrape will completely fail.  Looking at your kodi.log this is a bit bothersome...

`ERROR <general>: GetDirectory - Error getting /storage/Movies/Free Guy (2021)/Free Guy (2021).strm`

The entry for that is stored in your kodi database and appears can not be found.  Are you having to use the CM option **TMDbHelper Options** to then launch a player choice?  I can't see how a single select action could launch the content of an .strm when it can not even be found.  Also it would have been better to provide a kodi debug log as it contains a bit more info that may be helpful.

  I ran some tests and regardless if it's a Venom created .strm file, Venom created .strm file in TMDbHelper format, or a TMDbHelper created .strm file I could not reproduce this issue.  I even just added **Free Guy** to my library via TMDb Helper and had no problem with it at all.  I don't get any strm file error either.
   
<img width="695" alt="free_guy" src="https://user-images.githubusercontent.com/46383815/135521987-7e092cd5-645f-4e5c-b656-2fd94354af7d.PNG">
 
 Interestingly enough this is also in your log after the strm error
` plugin://plugin.video.venom/?action=play&amp;title=Free%20Guy&amp;year=2021&amp;imdb=tt6264654&amp;tmdb=550988`
That is honestly fine and has the title and year in it when that plugin path runs.  About the only thing I could do is make a custom release and log what data is being given to Venom and you'd have to install a zip and run that and then provide me with a venom.log of the results.  In the mean time I'd suggest enabling Venom's debug logging and post that to see if there's any indication what might be going wrong on your end.  Make sure it's set as follows.
<img width="1187" alt="venom_logging" src="https://user-images.githubusercontent.com/46383815/135523263-b507eb2f-51ba-410d-9c3d-518c0a56f134.PNG">

Shot in the dark but try clearing Venom's metacache.  When the play action is called I actually check the value of `meta` that is passed and then compare that with Venom's metacache db and also the Kodi library db and use the largest to assure the most complete meta is used for the scrape process.  TMDb Helper does not pass things like clearart and Venom's Source Select xml uses it so this meta check I mention helps to satisfy that.

**Comment by 123Venom** [comment]
> 
> 
> Seems more like an issue with the player than anything 🤔

ya but his player path in his log file appears correct.  The only thing I'm unsure of is if there's an error in the complete string that might muck it up, but it worked fine for me.  Url encoding always bugs out my eyes so I honestly did not study it and prefer to just log it..lol.

**Comment by Fubuz** [comment]
I have posted this issue since I am not alone with this exact problem. I saw some posts on reddit with people having the same issue (even with libreelec).

So i cleared the Venom metadata cache - still the same issue. I cleared all Venom cache - sadly, still the same issue.

The .strm file is definately there and for other movies (or tv shows) also:
![image](https://user-images.githubusercontent.com/69593507/135663322-c7155054-7586-4b13-8743-5f0d090e495e.png)

I have tried with TMDB helper player option as play with Venom (source select) and with the option to always choose the player when clicking on a movie or an episode. Other addons (fen, seren) scraped normal via TMDB helper and had no issues.

I have appended a kodi debug and venom log. I would be willing to test a custom release zip, if any useful info could be obtained.

Thank you for your help!
[venom.log](https://github.com/123Venom/plugin.video.venom/files/7269118/venom.log)
[kodi.log](https://github.com/123Venom/plugin.video.venom/files/7269119/kodi.log)

**Comment by 123Venom** [comment]
Install and run this test version.

https://github.com/123Venom/zips/blob/ee91cf8995e2de62f038824d0d5946e07b29d69a/plugin.video.venom-6.2.8.1.zip

I've added additional logging so I can see the data flow right from originating call and how it's handled.  Then post the venom.log file.  What we're looking for should match this....

<img width="1174" alt="free_guy" src="https://user-images.githubusercontent.com/46383815/135674623-34b8133a-8089-4022-a9d2-0a0d9ba8da28.PNG">

Stick with **Free Guy** for this test because I only added logging to handle a movie case.  It's interesting that I can not duplicate this issue on either a Windows or Android device and sorry but that's all the equipment I'm geared for testing.

**Comment by Fubuz** [comment]
I have installed the test version: Here is the venom log for the Free Guy. Hopefully, something can be figured out.

[venom.log](https://github.com/123Venom/plugin.video.venom/files/7271588/venom.log)

**Comment by 123Venom** [comment]
And here's the issue according to that new log data.

Mine
<img width="850" alt="mine" src="https://user-images.githubusercontent.com/46383815/135722407-ff32745e-a2db-4231-9e44-3dfc7211cce0.PNG">

Yours
<img width="809" alt="yours" src="https://user-images.githubusercontent.com/46383815/135722443-0ce4b1bf-9ea6-46b8-bd1c-6c4886a694c4.PNG">

The data passed in argv[2] is perfect.  Then a python urllib `parse_gsl` method converts this to a dictionary of key,value items.  Where you see `amp;` in your params it is not present in mine and it should not be there and causes it to break.  For some strange reason it seems it fails on Linux systems.  Why I do not know and that is not a Venom module and appears to be, imo, a bug I can't control.  Try this for me.... disable Venom's `reuselanguageinvoker` it's found here..
<img width="1020" alt="invoker" src="https://user-images.githubusercontent.com/46383815/135722548-ddf6e7f5-a00a-4a5d-8d65-bb08e32a5dc2.PNG">

Toggle that so it says false and try again.  If it works I don't need the log...if not post another log.  That option can be problematic and it might be related.

**Comment by Fubuz** [comment]
I have toggled the reuselanguageinvoker to "false". Sadly, the issue still remains. I have posted another venom log. I do remember, that before switching to a clean coreelec 19.2 rc3 I was on 9.2.7 version and I didn't have this problem.

[venom.log](https://github.com/123Venom/plugin.video.venom/files/7271830/venom.log)

**Comment by 123Venom** [comment]
I see in your log you performed a clear cache and that seemed fine but it also has no params where this `&amp;` is.  Do one more test for me.  In Venom's settings there are a number of `Help` file options that loads an xml text viewer window.  Can you try calling a few of those up.  Those have `&amp;` from the xml also...toss that log up as well.

**Comment by 123Venom** [comment]
I just replaced the occurrences of `&amp;` with `&` in the Venom Source Select player file only for a test if you also want to try that.
https://github.com/123Venom/zips/blob/9125eaebee0dc5f414e4c219481b38ac8876a971/venom.select.json

I tested in an ide and parse_qsl here had no issue splitting that up either way it was passed so it should not effect me...I'm about to test it myself to be sure but like I said ide confirmed it was fine.

It would seem that RC version you have may very well contain some changes I read that were done to **parse_qsl** and one of them is the `separator` character where this issue is happening.

**Comment by Fubuz** [comment]
I have clicked a bunch of those yellow -- Help -- links that are in different parts of Venom settings. Hope this is what you wanted me to do.
[venom.log](https://github.com/123Venom/plugin.video.venom/files/7271888/venom.log)

**Comment by Fubuz** [comment]
I will also now try the new venom player that you linked. Cheers

**Comment by 123Venom** [comment]
> 
> 
> I have clicked a bunch of those yellow -- Help -- links that are in different parts of Venom settings. Hope this is what you wanted me to do. [venom.log](https://github.com/123Venom/plugin.video.venom/files/7271888/venom.log)

yep..those all log good.

**Comment by Fubuz** [comment]
Wow Bingo! Once I replaced the venom player, it worked immediately. Thank you very much for your time in all this! 👍The issue is solved. I will also link this ticket issue to the people that were having the same problem on reddit.

**Comment by 123Venom** [comment]
Glad to hear it!  My test yielded no difference here so the **parse_qsl** version in py 3.8.5, that ships with Matrix, can handle it either way.  Seems your custom RC from CoreElec contains a newer version of **parse_qsl** that can no longer handle `&amp;`.  I will PR a new set of player files for TMDb Helper so that should resolve the issue.  There's a total of 4 files.

I also looked over a number of other player files for exo forks and all were using this `&amp;` and you may experience this issue from other addons.

**Comment by Fubuz** [comment]
I am currently using only Venom since I am really pleased with it.
I do have an additional question. For some time now my scraped result window does not show the 4k icon if the source is 2160p. All the other icons do show normal for other resolutions (1080p, 720p..). All the icons are there in the addons:
https://imgur.com/SGD57CV

Would you have any idea how to get the 4k icon back to show on scrape result or point me in the right direction?

**Comment by 123Venom** [comment]
so your 4k sources in the source select are just blank where the icon should be?  Another issue I've never seen but I have a hunch.  The image file is lower case.  Edit that and make it upper case and retest.  Looking at the code the quality is actually set as `4K` from FenomScrapers and if that fixes it then iit's a bad gaff on my part and I've gotten away with it.

**Comment by 123Venom** [comment]
Actually there's a few incorrect letter case conditions in there. Here's what FenomScrapers returns for a quality string for all
<img width="420" alt="quality" src="https://user-images.githubusercontent.com/46383815/135728729-7458c4ca-16e7-480d-a983-04992b49d8f2.PNG">

All I do is take that string and add `.png` to it to pull the icons from that `resolution` folder like so..
<img width="1002" alt="quality2" src="https://user-images.githubusercontent.com/46383815/135728751-9a8d4dbf-83e3-4fcf-b82c-dd8dfe813a93.PNG">

You can test edit those to match but I did make the changes here for next version.  I have a version with about 4 items now that'll prob get pushed out tonight so this will be in that.

**Comment by Fubuz** [comment]
The upper case did the trick. That's 2 in a row :)

Thank you so much for all the help and for the new versions of Venom! Have a great rest of the weekend!
