### ISSUE TITLE
All Trakt personal lists return Nothing was found

### ISSUE THREAD

**Issue by lastmoexit** [123Venom/plugin.video.venom#133]
Operating System: Android
Device: Nvidia Shield
Version of Kodi: 19.1
Version of Venom add-on: 6.2.9
Country: USA
Debrid services in use: Real-Debrid & Premiumize

repeated "resync with Trakt" message, as well

love the addon, btw

**Comment by 123Venom** [comment]
>repeated "resync with Trakt" message, as well

Please provide a screenshot of this message as no .py, .xml, .po file of Venom's produces such a message I've scanned for, nor recall.

There is also nothing called `personal lists` in any .py, .xml, .po file as well.

  So you are going to have to screen shot and be MORE specific please.  Picture is worth a thousands words and you failed.  Your posted issue was BEYOND vague and I nearly deleted it because I'm not chasing my tail on guessing games with my spare time!!  Your posted issue was TERRIBLE...little more effort put in would not kill you and that's more than I'm going to exhaust on the next vague response of yours or it's instantly deleted if you pull this again.

Sorry if harsh but this was comical!

**Comment by lastmoexit** [comment]
First, I'm sorry that I did not give enough info. This is my first time doing this and I thought that I had followed the rules in the readme file. I'm sorry I didn't. This is new to me and I would like to correct my mistakes. I'm not sure how to move the logs from my shield to my pc since they aren't directly connected.

Please bear with me. I don't want to offend. I'm older and disabled with memory problems. I'd like to do this correctly. Would you help walk me through what I need to do?

When I said Trakt personal lists, I'm referring to lists that I create. All of the list names are there, but Venom reports them all as empty.

Thank you for your time creating the addon and time expended helping me. I want to do this right.

**Comment by 123Venom** [comment]
Honestly I'll try but like many my free time is limited.  Is your newly created list movie only, show only, or combo?  Can you screen shot the listing so I know where you are viewing?  In the mean time what I did, so you can clearly see I started this process fresh,  is I made a new trakt list using your screen name..lol.  That way ya know it's bran new.  Before new list creation I get this for

`My Movies-My Lists`
<img width="752" alt="22d" src="https://user-images.githubusercontent.com/46383815/135970266-88665141-3af4-4a53-b315-27265c3ebd03.PNG">

Then I made a new list on the Trakt website using your screen name of `lastmoexit` and added 5 movie titles to it.  Upon returning to Venom the list did not show, I did not expect it to and here's why....Venom sync's this data on a service clock every 15mins.  If you can not wait for this sync to take place there is an option in `Tools-Trakt Management Tools-Force Trakt Sync to local database` that will force it to take place immediately!  Upon forcing this sync I was greeted with this...

<img width="596" alt="22e" src="https://user-images.githubusercontent.com/46383815/135970638-90241991-ba71-4cf6-8e48-02752368564b.PNG">

There's the new list and even before I enter this list I took a snapshot of what the items should be inside and got this...
<img width="1266" alt="22c" src="https://user-images.githubusercontent.com/46383815/135970733-877769db-9565-486e-843f-328e19b058cf.PNG">

Now lets go in and see if content matches...
<img width="1178" alt="22f" src="https://user-images.githubusercontent.com/46383815/135970874-292630fb-6995-4cbb-be55-2399ed96cc3a.PNG">

BOOM!  dead match for me and found not a single issue.

**Comment by lastmoexit** [comment]
Wow! Thank you so much for the quick and detailed response. I'm going to try and gather together the screenshots to better explain the problem I am having. It might take a bit, so please bear with me.

Thank you again for your time and help.

**Comment by 123Venom** [comment]
ohh I'm off to bed so post away I'll peak tomorrow.  I would try that `Force Trakt Sync to local database` option because you might be experiencing the 15 minute service clock it take to auto update the data...might not be to but worth the shot because that is what I needed to make it show up right away.  Allot of ppl do not realize the service clock is 15min intervals.

**Comment by lastmoexit** [comment]
okay, i did just do a fresh kodi install and only added Venom and if I click on Movie Lists or sometimes just clicking on the addon to use it I see a quick popup on top right of my screen that says Trakt Re-authenticate Trakt Access with the Venom icon

**Comment by 123Venom** [comment]
did you auth Trakt in the My Accounts addon?  When you do that you need to hit `OK` in My Accounts, then Venom settings will come back up and you **MUST** hit OK again.  Both must be done.  In Venom settings under Trakt category you can bring up your Trakt account info...does it load?

**Comment by lastmoexit** [comment]
yes, I authorized Trakt, Premiumize and Real Debrid in My Accounts. Also authorized API's of Fan Art, TMDb, TVDb, IMDb and Furk.

**Comment by lastmoexit** [comment]
don't let me keep you up, please. you've already been a great help
 I need to go to bed, too

**Comment by lastmoexit** [comment]
I will do more to gather new info for you and add it as I get it, if that's okay.

**Comment by 123Venom** [comment]
Do you get this to come up from settings?

![Trakt](https://user-images.githubusercontent.com/46383815/135981609-d2197f1c-91a8-4a07-a01f-3e28b4c7f6d4.PNG)

**Comment by 123Venom** [comment]
Open it from there

![27b](https://user-images.githubusercontent.com/46383815/135981907-04af0051-7469-4172-b4cb-3e885eb143e1.PNG)

**Comment by lastmoexit** [comment]
no, I don't. It has my Trakt username filled in, but when I click on Account Info nothing happens

I'm able to pull up all other Trakt items throughout the addon. It's only when I try to do Movie Lists and TV Show Lists under My Movies and My TV Shows, respectively, that it will show all the names of the lists I've made, but they are all empty

**Comment by 123Venom** [comment]
click that info again and wait..mine just took 5secs before it loaded the info.  Sometimes Trakt is fast to respond to the request and sometimes slow.

You're saying the custom lists you made are showing up but none of them load?  That fried I've never seen that.  You have to be doing something wrong....especially hearing you say the account info is there but nothing loads there either

**Comment by lastmoexit** [comment]
I did that while I wasn't typing and then I went into the My Accounts addon and tried it there. In My Accounts addon it shows my Trakt username but clicking on Account Info does nothing. Same as in Venom. Could it be a problem with My Accounts addon?

**Comment by 123Venom** [comment]
doubtful...try to revoke Trakt auth and setup from scratch again.  If same try a restart of Kodi

**Comment by lastmoexit** [comment]
The strange thing about this is when I use Kodi with Venom, Fen and Seren it only happens with Venom. Fen and Seren and Trakt all play nice.

**Comment by 123Venom** [comment]
Fen uses My Accounts so if Fen works right then the sync to Venom should also be fine

**Comment by 123Venom** [comment]
> Should I do it directly accessing My Accounts addon or accessing My Accounts through Venom I'd call it from Venom..if you go directly to MA first then you have to use the manual sync method for Venom to fetch the account setup info

**Comment by lastmoexit** [comment]
Okay, that is how I normally do the setup.

**Comment by 123Venom** [comment]
> Success with resync and Account Info showing through Venom. Should I check to see if Movie Lists is now working correctly?

why of course that'd be next step

**Comment by lastmoexit** [comment]
bummer here. sorry again. it has all of my list titles, but if i click on any of them it says in a popup "Nothing was found"

**Comment by 123Venom** [comment]
ok...take one list...is it a public list I can access on Trakt?  give me the link and let me look at it..long as you did not set the list to be `private`

**Comment by lastmoexit** [comment]
okay, hold the phone. i think all my lists might be set to private. could that be the cause? and if so, why can other addons read the lists?

**Comment by 123Venom** [comment]
your own lists if private should load...that ain't what I meant.  I meant if you share the link with me I can't access it if it's private

**Comment by lastmoexit** [comment]
https://trakt.tv/users/bouja-houda/lists/007-james-bond?sort=rank,asc

direct link only has 6 in it

**Comment by 123Venom** [comment]
ok..what i'm going to do is `Like` your list.  If your list now shows for me in Venom you absolutely have something setup goofy there..but lets see first.

**Comment by lastmoexit** [comment]
wouldn't surprise me if it's my setup ...lol

**Comment by 123Venom** [comment]
OK..see the thumbs up?  I Liked it and now it will be available for ME inside Venom in my `My Movies-Liked Lists`

<img width="1020" alt="199b" src="https://user-images.githubusercontent.com/46383815/135986155-2ed78194-d522-40fe-9ca1-7285268ba23b.PNG">

**Comment by lastmoexit** [comment]
btw, your helping my is fantastic! thank you

**Comment by 123Venom** [comment]
OK we got somewhere.  Your list appeared for me but when clicked it...boom...empty.  All my other lists are loading fine but yours and that is very odd.  I need to digest this more and log responses to see what Trakt is returning.  I will come up with the answer.

<img width="904" alt="199c" src="https://user-images.githubusercontent.com/46383815/135986489-7afaf9df-1a52-4aee-898f-b7323737db8e.PNG">

**Comment by lastmoexit** [comment]
okay, i have something to add. if that's alright

**Comment by lastmoexit** [comment]
i really can't thank you enough for all your help. It's very awesome.

**Comment by lastmoexit** [comment]
are we still working on this now or will we pick up later today after some rest? either way is fine with me.

**Comment by 123Venom** [comment]
I'm still looking at it.  The url for the request seems proper but the api response returns None.  I need more time.  Prob won't have an answer today..I'm getting tired and need bed

**Comment by lastmoexit** [comment]
Okay. Will pick up later then. Thank you.

**Comment by 123Venom** [comment]
Something does seem off with your list and I will find it.  The api response is None but any other list returns data as you can see..just not yours

<img width="1430" alt="list_log" src="https://user-images.githubusercontent.com/46383815/135990626-0b9b286c-69f8-47d2-8273-ed5ec39277b9.PNG">

**Comment by 123Venom** [comment]
how long ago did you make this list?

**Comment by lastmoexit** [comment]
That one is rather recent. I have a list I made just yesterday when I was trying to figure this out called venom test. I can give the URL for it or give you an older one, whichever if you need it. There venom test list comes back empty, also, as do all of my lists.

**Comment by lastmoexit** [comment]
Should I test what happens if I like my own list?

**Comment by DaisyF8** [comment]
In another channel the dev said an update will come out adressing this issue (just letting you know since it's late).

**Comment by lastmoexit** [comment]
I'm not alone with this?

**Comment by 123Venom** [comment]
@lastmoexit yes I have fixed the issue with some Trakt lists not loading.  It's a rare case that honestly only effects a few list types and your `dot` separator in your name triggered it to show up.  Nothing for you to worry or change it will be fixed in Venom next release.

What @DaisyF8 was meaning is that the topic of this issue came up in another chat room and had a few users helping to run some tests for me.  I made note there that I had solved it so it was just being conveyed to you.

**Comment by lastmoexit** [comment]
Thank you soooooo very much for deciding to help me. And I will work on my poor posting skills. It's the least I can do seeing you used a big part of your valuable time helping a beginner. It makes me all the more appreciative for the work and effort you put into the addon and offering it en masse no charge. Stay excellent! 👍🙂

**Comment by 123Venom** [comment]
np...update should get pushed tonight if all thing go well in this household..lol
