### ISSUE TITLE
Trakt Library Issue

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#136]
Hey,

I'm hoping you can point me in the right direction where I am going wrong.....

So, I have created my own list through mdblists.com which then sync to my trakt account. 

I am try to add these to my local library to make kodi run a millions tines faster.

Now I have gone into settings and created the venom movies for library, then when I go into My Movies... Movie List... long hold button over the trakt list ie Movies Trending...  add to library... am I sure YES, I then check the movies folder and only ever have 60 movies in it instead of my list which contains 248. 
Any help????

Cheers in advance

**Comment by 123Venom** [comment]
Largest list of my own I have is 27 items and it just imported all without issue.  Could be an item meta gaff in one of the items causing it to terminate..idk.  I'm sure not replicating a 248 item list to dissect it without any logs given per the readme.  You could try the list import method under `Tools-Library-Trakt: Import Movie xxx`.  Without the required log files it's anyone's guess.

**Comment by adamosborne83** [comment]
> Largest list of my own I have is 27 items and it just imported all without issue. Could be an item meta gaff in one of the items causing it to terminate..idk. I'm sure not replicating a 248 item list to dissect it without any logs given per the readme. You could try the list import method under `Tools-Library-Trakt: Import Movie xxx`. Without the required log files it's anyone's guess.

Cheers for the reply, and I know it was a stab in the dark without a log, but there are no errors or anything. It just does not import the whole library.

Excuse my ignorance with logs, but will it show you what's going on even without an error message??

**Comment by ShaVerZ** [comment]
May be a good idea to send the Venom Logs but also the My Accounts Addon Logs in case something is showing there.....On 16 Oct 2021 09:00, adamosborne83 ***@***.***> wrote:

Largest list of my own I have is 27 items and it just imported all without issue. Could be an item meta gaff in one of the items causing it to terminate..idk. I'm sure not replicating a 248 item list to dissect it without any logs given per the readme. You could try the list import method under Tools-Library-Trakt: Import Movie xxx. Without the required log files it's anyone's guess.

Cheers for the reply, and I know it was a stab in the dark without a log, but there are no errors or anything. It just does not import the whole library.
Excuse my ignorance with logs, but will it show you what's going on even without an error message??

**Comment by adamosborne83** [comment]
Https://paste.kodi.tv/amoxizidef

**Comment by 123Venom** [comment]
I thought this was a movie list you made?  The log error line 560 is a call to import TV Shows.  What is your trakt username and list name you created?  I can try and like your list to see if I can import it and find out what the issue is.  You might also give TMDB Helper's library integration a try as many use that now.

**Comment by adamosborne83** [comment]
> The import list method for liked lists is broken...lol. Looks like when I enhanced the traktsync methods I no longer needed the url and removed it but neglected that list import methods for library integration does in fact still need it. This is why I utterly hate library integration....I do more harm than good forgetting about something I never use so it does not get retested and checked because of time investment in doing so. You do not have to use liked list import method since it's your own and you might not even notice that this import is broken. You should be able to use the **Trakt:Import Movie User List** since it's your own.

Thank you so much for looking into this.

I think I'm going to give library a miss... where I use a firecube, then attach a USB nothing gets picked up correctly. Seems more trouble than it's worth.

I just wanted instant load movies on my widgets haha.

**Comment by 123Venom** [comment]
lol..tried to catch you before adding that many.  It's just more to clean out for me and only need a couple added for the test.  I'll let ya know in a minute.

**Comment by adamosborne83** [comment]
> Ya looks like I did not give the api enough time. Did you keep on adding titles cause the count is up to 432?
> 
> <img alt="15d" width="1146" src="https://user-images.githubusercontent.com/46383815/137795335-f844c0d1-043e-4a5a-8e12-c862a37365b6.PNG">

Haha apologies for adding soooo many. 
![Screenshot_20211018-203629_Samsung Internet](https://user-images.githubusercontent.com/78307374/137795591-c42fb3d5-e42e-4634-9077-1a26df18a907.jpg)

**Comment by 123Venom** [comment]
429 vs. 432...still doesn't check out.  Did you add a few more since that pic?

**Comment by adamosborne83** [comment]
> 429 vs. 432...still doesn't check out. Did you add a few more since that pic?

No it's still 429, do you think there is a possibility where I added another genre to my list the movies my had duplicated in yours and not deleted????

**Comment by 123Venom** [comment]
> > 429 vs. 432...still doesn't check out. Did you add a few more since that pic?
> 
> No it's still 429, do you think there is a possibility where I added another genre to my list the movies my had duplicated in yours and not deleted????

idk but I'm not hunting through 432 items searching for 3 dupes..that you can do with the test version I'll upload.

**Comment by adamosborne83** [comment]
Apologies. Long day at work a few too many glasses 🥂

**Comment by adamosborne83** [comment]
> once you start fresh it will start off at 245 for you and build as you add new titles...it just won't remove them.

No that's fine. My library will be ever growing so not an issue. 
If you know, out of interest. 
Obviously as you can see I've got Genre lists.... so my widgets will be those particular genres..... BUT in regards to trending........

Is it possible that if I point a widget at that list, will it load from Internet or from my library?
In regards to speed.

Totally off subject and issue

**Comment by 123Venom** [comment]
Test version.

https://github.com/123Venom/zips/blob/5246d55cb06c057b4091638e665645eebcb19976/plugin.video.venom-6.3.1.1.zip

**Comment by 123Venom** [comment]
fresh import from nada gave me 249 items from your list...no idea what ya got in there and why it's not 245 you said you reduced it to...happy hunting..lol

<img width="1266" alt="15f" src="https://user-images.githubusercontent.com/46383815/137832618-633fb712-9510-43fe-af83-1f74adf9ab63.PNG">

**Comment by adamosborne83** [comment]
Yes it's me again...... quick question. As I am trying library integration again........ I've figured out how to change paths for thumbs etc....... is there a wayyoj can enhance the add list section, so I can add multiple of My Lists all at once instead of having to go into 1 by 1 and have it to update at a certain time?
