### ISSUE TITLE
No Rotten Tomato, metacritc rating

### ISSUE THREAD

**Issue by Jonnygrunge** [123Venom/plugin.video.venom#139]
This is happening on any version after 19.0, trailers also do not work. I am using the Netflix view. 
Android TV on a Shield (new version pro) 

Everything works fine on 19.0.

Jon.

**Comment by Tikipeter** [comment]
How is that a Venom issue? Have you posted in the wrong github by accident?

**Comment by xyzfre** [comment]
Not sure if I'm correct but I think ratings come from the skin you're using or certain dependencies that need certain APIs￼￼
