### ISSUE TITLE
Dependency on script.module.requests could not be resolved

### ISSUE THREAD

**Issue by nitinjs** [123Venom/plugin.video.venom#140]
when I try to install venom addon I get the error
`Dependency on script.module.requests could not be resolved`

![image](https://user-images.githubusercontent.com/298479/140519818-cdedfd99-886f-4e00-a0e8-e8ae2239448d.png)

I'm on windows 11 with kodi-19.3-Matrix-x64

**Comment by 123Venom** [comment]
with no kodi.log or venom.log attached I am not guessing on an issue I've never seen occur before.  All and addon has to do to add requests as a dependency is

```
<requires>
    <import addon="script.module.requests" />
</requires>
```

The rest then is on Kodi as it's part of the kodi repo to utilize.  If this simple means fails I'd be inclined to think your setup is hosed.  Again without logs it's a guessing game so provide both or I can not help you.
