### ISSUE TITLE
Enhancement: Trakt

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#146]
Good Evening,

Hope you're well.

Feel free to tell me to jog on.....

In the My Shows aspect in regards to trakt, you have various options, finish watching, progress etc etc.

Is there anyway you can add the option in regards to what I have just watched, instead of it being the episode, it can be the show title, then hives me the option to go in and choose the episode. 

Does this make sense?

I know seren has the option, I'm just wondering if you could add it?

I'm happy to send a pic if I have made no sense at all :-)

**Comment by drinfernoo** [comment]
"Recently Watched Shows"?

**Comment by adamosborne83** [comment]
> "Recently Watched Shows"?

So in seren its 'recently watched' where it gives the title of what you've been watching therefore allowing me to go in and browse as such

Venom, only seems to show the episode itself

**Comment by drinfernoo** [comment]
You're requesting "Recently Watched Shows"? Venom isn't Seren.

**Comment by adamosborne83** [comment]
> You're requesting "Recently Watched Shows"? Venom isn't Seren.

I know that, I was just asking if it could be added. It's no big deal, just an enhancement if possible.

**Comment by 123Venom** [comment]
You can use the history list as is and call up the context menu to select item **"Browse Series"** to achieve what you want.  I really do not desire to add another list in the **My TV Shows** section
