### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by Arthur1967** [123Venom/plugin.video.venom#147]
I just installed the new update when I hit my lists or my like list I get nothing but collections and everything else is working and my doing something wrong

**Comment by 123Venom** [comment]
"my lists"?  There is no list of that name.  Each of the "My Movies" and "My TV Shows" both have a "My Liked Lists" and loaded fine for me on two different devices.  Notice how I was a bit more descriptive there naming gui menu items? You also provided no logs so it's a guessing game I won't do.
The latest update can not have an effect on the gui menu items.  The only thing touched for code was one module, the "sources" module and that has nothing to do with gui menus.  The update was about the smallest update I've done in ages.  Something else caused it.  Try clearing the cache.

**Comment by Arthur1967** [comment]
OK I'm not home right now but I'll try it later again
