### ISSUE TITLE
[Request] Add Easynews section to Premium Services, with Search if possible

### ISSUE THREAD

**Issue by DaisyF8** [123Venom/plugin.video.venom#148]
The debrid sections are present, but Easynews is missing.

I'm asking hoping you would implement a direct Search-function. And a Search History for EasyNews would be nice. ATM for Stephen Colbert (a daily show, difficult with usual addons) I use another addon. Would be nice to have a backup.

**Comment by 123Venom** [comment]
Good point.  I'll consider adding an EasyNews gui for search and history.

**Comment by DaisyF8** [comment]
Thx :)
