### ISSUE TITLE
Api Language

### ISSUE THREAD

**Issue by djdirty60** [123Venom/plugin.video.venom#153]
Language fallback not working.

I use the Dutch language, but if it is not present for a movie the plot remains empty but there is an English plot for it so I think the fallback for the language does not work

**Comment by 123Venom** [comment]
Sure would be allot faster for me to check if you gave me one of these title cases vs. hunting.

**Comment by 123Venom** [comment]
I dug around a bit.  There is no translation fallback in Venom when the meta comes from TDMb...I never coded one and not sure where you thought there was one?  Just looking over my **tmdb** indexer would be a substantial amount of time to make one and allot of re-write work.  Frankly if you need fallback when it's unavailable you may be better off with another addon like **FEN**, he does a much better job and doesn't mind investing allot of his free time on foreign meta.  I have however added this to my notes for future consideration.
