### ISSUE TITLE
MP4 files 

### ISSUE THREAD

**Issue by tiagomiguel1994** [123Venom/plugin.video.venom#155]
Good afternoon, i want to ask a question.. why when i go to download a real debrid movie by venom the files are all in mp4?  
I am 100% sure the original file is in MKV.  
Greetings

**Comment by 123Venom** [comment]
my bad...the extensions had a typo so it was using the mp4 fallback.  Fixed for next update

**Comment by tiagomiguel1994** [comment]
Thank you very much, have a good new year.

**Comment by 123Venom** [comment]
I have to give credit to @Tikipeter for this one though.  He did me a favor and peaked before I had a chance to get to it.  It's nice having decent devs not ego driven and lending a helping hand.
