### ISSUE TITLE
Ability to choose HEVC files?

### ISSUE THREAD

**Issue by sabre6** [123Venom/plugin.video.venom#158]
Really like your work. Thank you!

You have ability to exclude HEVC files. I like to use them. Is there a way to move HEVC files to the top / or prefer them with your addon?  

Thanks

**Comment by 123Venom** [comment]
I've added it for next release against my better judgement..lol

**Comment by sabre6** [comment]
Oh thank you. If you dont want it, please do not feel the need for it. We will get by.
