### ISSUE TITLE
trakt.tv Section

### ISSUE THREAD

**Issue by ronfrankhill** [123Venom/plugin.video.venom#159]
I am enjoying the section that handle trakt.tv especially in the TV section of trakt progress that l use a lot in order to keep up to date with. Thank you.

**Comment by xyzfre** [comment]
I agree specifically Upcoming Progress is GREAT feature instead of having in Progress shows all in one section

**Comment by 123Venom** [comment]
Thanks for the kind words folks.  Ohh and **Season Premiers** is a nice one also.  I can peak and see when my shows new seasons start back up again.

**Comment by xyzfre** [comment]
Season Premiere is a GREAT feature as well ,,Venom it's self is AMAZING,,Thank you for all the hard work
