### ISSUE TITLE
Search via http

### ISSUE THREAD

**Issue by Alfiegerner** [123Venom/plugin.video.venom#161]
Could anyone point the way to what an api search over http might look like?

E.g. for seren we can use ActivateWindow and the following param plugin://plugin.video.seren?action=showsSearch&actionArgs=$(searchString}'.

Thanks!

**Comment by 123Venom** [comment]
```'ActivateWindow(Videos,plugin://plugin.video.venom/?action=tvSearch,return)'```

I'm not sure what you are looking to do with this and I do not use this call myself so you'll have to test it.

**Comment by Alfiegerner** [comment]
Sorry I wasn't clearer, I was looking to pass in a search string, e.g.:

'ActivateWindow(Videos,plugin://plugin.video.venom/?action=tvSearch,return&searchString=Wandavision)'

Which would return a list of matching shows.

Use case here is using Google home / other downstream systems to search for movies or TV shows by keyword.

**Comment by drinfernoo** [comment]
@Alfiegerner What mechanism are you using to pass that call from Google Home?

**Comment by 123Venom** [comment]
ok if you want to pass your own query string then you'd use...

```'ActivateWindow(Videos,plugin://plugin.video.venom/?action=tvshows&url=https%3A%2F%2Fapi.trakt.tv%2Fsearch%2Fshow%3Flimit%3D40%26page%3D1%26query%3DWandavision,return)'```

Unfortunately Venom passes the search url and it MUST be quoted per above.  Again I added this to a sub menu to run the command and it loaded results for `Wandavision` and worked fine.  You can tweak the results limit also in that string.  It's hardcoded to 40. `limit%3D40` `%3D` is `=` sign so you can tweak the `40` in that string to desired value if you want.

**Comment by Alfiegerner** [comment]
Perfect! Thanks so much.  One of the fave features of our house, searching for movies via google home: 

https://github.com/OmerTu/GoogleHomeKodi

I'll make PR to add Venom searches in addition to the Seren ones I added.

**Comment by Alfiegerner** [comment]
> @Alfiegerner What mechanism are you using to pass that call from Google Home?

See link above, I have IFTTT pass a command to one of three Kodi instances on our house, conveniently within the free 3 applet IFTTT limit.

So saying 'Lounge Kodi search movies for  %'  triggers 
IFTTT applet for 'Lounge kodi' which then passes the query string and specified Kodi install as params to the code linked above.  Saying 'Downstairs Kodi' activates different applet which sends a param to use different Kodi install.

Let me know if you want more info and I'll share my config.

**Comment by 123Venom** [comment]
just curious on what you are using to insert the query term you want?  `Wandavision` was easy and nothing to quote there but you'll need a quoted version of query term...just mentioning it.

**Comment by Alfiegerner** [comment]
Thanks @123Venom , i think this currently handled somewhere between the IFTTT and the Google home Kodi project, but will make sure to check.

**Comment by Alfiegerner** [comment]
P.s. The construction of the param sent to Kodi is what the PR to the kodi google home project will do, so we also have formatting / urlencoding opportunities there.

**Comment by 123Venom** [comment]
then you should be golden!

  I misused used the term **quoted** because from python `urllib.parse` we uses the `quote and `quote_plus` methods to get url encoding, but you got me I can tell...lol
