### ISSUE TITLE
Trakt Library (me again)

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#162]
Yes it's me again...... quick question. As I am trying library integration again........ I've figured out how to change paths for thumbs etc....... is there a way you can enhance the add list section, so I can add multiple of My Lists all at once instead of having to go into 1 by 1 and have it to update at a certain time

**Comment by 123Venom** [comment]
Prob would result in more time investment on my part than I'm interested in investing.  Sorry bud I'm sort of only doing small maintenance for library integration at this time as many seem to have moved to TMDb Helper.  I don't know if he offers multi list importing at once or not.
