### ISSUE TITLE
MPAA Ratings 

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#163]
I do not suppose you fancy a little enhancement of giving options for MPAA ratings? Love to be able to change it to UK 🇬🇧 😌

**Comment by 123Venom** [comment]
Yes I was asked to add this and it is planned to be included in next update.

**Comment by adamosborne83** [comment]
> Yes I was asked to add this and it is planned to be included in next update.

You Sir, are a gent. I did try and do a search for it prior to asking.
