### ISSUE TITLE
Library Question......

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#164]
Promise this will be the last Question for library. 

We've previously established that I need to go into tools and import from Trakt My List..... so for example if I import Movies Trending...... this will obviously update new films daily being added to the list. 
Will this update through Venom daily? Just I cannot see anything that shows me what's selected. 

Or if it is just a 1 off update. 

Hope I make sense. 

PS I can see why you hate Library..... I like the prospect, but bugger me, the logistics are a nightmare.

**Comment by 123Venom** [comment]
The intent is that once you import a list, as you explained you did, Trakt api keeps a record `updated_at` so the service should detect the change and perform a re-sync of the list so anything newly added should be brought in and the library sync occurs at 6hr intervals.
Beyond that bud I'm afraid to break it to you that Libray Integration is something I highly desire to remove from Venom...never used it and I never will.  I've only maintained it for users but as my free time seems to keep growing shorter and shorter I find the need to stop supporting features this family here has no need for.  I'm not meaning to sound harsh but trying to be as honest as I can on the matter.  My opinion is if Library Integration is what you truly need, and Venom's current state does not suffice that need, then maybe it's time you look into TMDb Helper, or even The Oath, as both maintain it regularly beyond what Venom does.

I'd honestly move towards a skin supporting widgets and use Trakt Progress/NextUp widgets.  Trakt lists for widgets I'm sorry to say smoke Library Integration and why none of us here have a need for it.

**Comment by adamosborne83** [comment]
> The intent is that once you import a list, as you explained you did, Trakt api keeps a record `updated_at` so the service should detect the change and perform a re-sync of the list so anything newly added should be brought in and the library sync occurs at 6hr intervals. Beyond that bud I'm afraid to break it to you that Libray Integration is something I highly desire to remove from Venom...never used it and I never will. I've only maintained it for users but as my free time seems to keep growing shorter and shorter I find the need to stop supporting features this family here has no need for. I'm not meaning to sound harsh but trying to be as honest as I can on the matter. My opinion is if Library Integration is what you truly need, and Venom's current state does not suffice that need, then maybe it's time you look into TMDb Helper, or even The Oath, as both maintain it regularly beyond what Venom does.
> 
> I'd honestly move towards a skin supporting widgets and use Trakt Progress/NextUp widgets. Trakt lists for widgets I'm sorry to say smoke Library Integration and why none of us here have a need for it.

I just want to say that Library is working amazingly. 
I know you want to give it in, but it is perfect right now. 
You are awesome 👌
