### ISSUE TITLE
Trakt issue after most recent update

### ISSUE THREAD

**Issue by zemely** [123Venom/plugin.video.venom#165]
Hello,
OK, maybe I am missing something but after most recent Venom addon update, none of my Trakt TV shows have any episodes. I went through the update notes, did synch Trakt database, nothing. KODI 19.3, NVidia Shield. Tried other addons, everything works fine.

Please, help

**Comment by 123Venom** [comment]
I just checked all lists in the My TVShows and no issues here. Did you try the obvious cache and metacache clear, as well as a restart.  Post debug venom.log

**Comment by zemely** [comment]
Yes, I cleared all cache, synch Trakt database to local, restarted KODI. Seren works fine. I will try to post debug file, not sure how to do it.
I am not talking about show lists, I have Watchlist and Collection but when I go into the show seasons, there are no episodes.
I tried Chopped(watched it on Venom last week) and few others, none of the seasons have any episodes
    On Sunday, January 23, 2022, 11:09:42 AM EST, 123Venom ***@***.***> wrote:  
 
 


I just checked all lists in the My TVShows and no issues here. Did you try the obvious cache and metacache clear, as well as a restart. Post debug venom.log

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123Venom** [comment]
I understood what you said about episodes not loading for you but those trakt items are accessed from My TVShows so I had it right.  I can't find any show in my own trakt watchlist that will not load the episodes.  I even searched for you show Chopped and season and episodes loads fine hereSent from my Galaxy
-------- Original message --------From: zemely ***@***.***> Date: 1/23/22  11:20 AM  (GMT-05:00) To: "123Venom/plugin.video.venom" ***@***.***> Cc: 123Venom ***@***.***>, Comment ***@***.***> Subject: Re: [123Venom/plugin.video.venom] Trakt issue after most recent update (Issue #165) 

 Yes, I cleared all cache, synch Trakt database to local, restarted KODI. Seren works fine. I will try to post debug file, not sure how to do it.

I am not talking about show lists, I have Watchlist and Collection but when I go into the show seasons, there are no episodes.

I tried Chopped(watched it on Venom last week) and few others, none of the seasons have any episodes

    On Sunday, January 23, 2022, 11:09:42 AM EST, 123Venom ***@***.***> wrote:  

 

 





I just checked all lists in the My TVShows and no issues here. Did you try the obvious cache and metacache clear, as well as a restart. Post debug venom.log



—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marcelmah** [comment]
I had the same, I cleared all cache and even Trakt cache, no dice.
Next day everything was fine again.

**Comment by 123Venom** [comment]
Mystery....I checked with users in our keybase group and nobody responded back as to having seen this issue.

**Comment by zemely** [comment]
OK, not sure what has happened that day, maybe I was a bit impatient and should have waited longer but yesterday everything was perfect, all episodes were there, used Venom the whole day, no issues. The best addon!!!!!
Thank you very much and sorry for wasting your time
    On Monday, January 24, 2022, 09:24:24 AM EST, 123Venom ***@***.***> wrote:  
 
 


Mystery....I checked with users in our keybase group and nobody responded back as to having seen this issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zemely** [comment]
Right, the same thing I had: Saturday had an issue, yesterday everything was perfect. Maybe we have to allow more time for things to update or something.

    On Monday, January 24, 2022, 04:40:53 AM EST, Marcel ***@***.***> wrote:  
 
 


I had the same, I cleared all cache and even Trakt cache, no dice.
Next day everything was fine again.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xyzfre** [comment]
Sometimes it could've to do with Trakt servers or something it's always good to wait 24 hours when issue pop up with Trakt ,, because ever since the last update from venom on my end I see a very big speed improvement Venom is an amazing add-on always grateful for all the hard work that goes into it

**Comment by zemely** [comment]
Oh, absolutely, Venom is my #1 addon. It's just the message said that synch has been completed so I had expected it to be synched.Anyway, worked fine next day
    On Monday, January 24, 2022, 12:11:09 PM EST, xyzfre ***@***.***> wrote:  
 
 


Sometimes it could've to do with Trakt servers or something it's always good to wait 24 hours when issue pop up with Trakt ,, because ever since the last update from venom on my end I see a very big speed improvement Venom is an amazing add-on always grateful for all the hard work that goes into it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
