### ISSUE TITLE
Just an FYI

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#170]
Ok, this is just more for information, and I do not want to send you the log, as I do not want to PI*S you off and give up on library integration all together, as I love your set up.

So I cleaned Kodi back to basic and just used Estuary, then installed Venom, and i did install Skin Helper and Widgets, so I then imported my user list from Trakt, which contained around 4000 movies.
I then checked over 2000 (I was bored) to which they all worked fine.
I then had a thought, I had not enabled the Auto Update, so I then created the Venom Folders, then added a few movies to my Trakt list, left it over night as I remember you mentioned that it updates roughly every 6 hours, so I checked this morning, and all the new movies that updated through the auto update did not work.

So I deleted the files, then did a clean, then just went onto import user list again, the movies then downloaded again and PLAYED!

I now know how to manage this :)
I just wanted to give you the info I found out, as I really do not want you to take this awesome feature away :)

**Comment by jaimsitecom** [comment]
> Ok, just this more for information, and I do not want to send you the log, as I do not want to PI*S you off and give up on library integration all together, as I love your set up.
> 
> So I cleaned Kodi back to basic and just used Estuary, then installed Venom, and i did install Skin Helper and Widgets, so I then imported my user list from Trakt, which contained around 4000 movies. I then checked over 2000 (I was bored) to which they all worked fine. I then had a thought, I had not enabled the Auto Update, so I then created the Venom Folders, then added a few movies to my Trakt list, left it over night as I remember you mentioned that it updates roughly every 6 hours, so I checked this morning, and all the new movies that updated through the auto update did not work.
> 
> So I deleted the files, then did a clean, then just went onto import user list again, the movies then downloaded again and PLAYED!
> 
> I now know how to manage this :) I just wanted to give you the info I found out, as I really do not want you to take this awesome feature away :)

Thanks for this!  I’ll do the same from now on whenever this issue comes up. I also hope that the Library integration doesn’t get scrapped. Love this feature. Fen took it out and had to go thru TMDB helper to play library items via FEN. 

Again, ty.

**Comment by 123Venom** [comment]
@adamosborne83 that makes sense and if and when I get the time I'll see if I can replicate that method.  In the mean time it'd still be more helpful if you post the logs I've asked you for.  If I asked for them I'm not going to get pissed off for you posting them.  I'm sorry if I come across that way but truthfully I've never used library integration nor ever will.  I use to put a decent amount of my free time into it for people but as time went on life said it was time to start limiting my time from features I'll never use.  I'm not sure why you guys insist on using library integration for streaming content.  I do stand corrected...I did use library integration about 4-5 years back.  I did not for streaming, strm files however.  It was a local storage of rips so they were all mkv files but I gave up maintaining that.  That imo is what library integration is meant for.

**Comment by 123Venom** [comment]
@adamosborne83 youur log is much cleaner than before!!  One I would do is enter api keys into metadatautils as you are getting Rate Limiting.

Also your log is still showing read issue
```2022-02-09 16:53:55.023 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/Austin Powers International Man of Mystery (1997)/
2022-02-09 16:53:55.580 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/Collateral Damage (2002)/
2022-02-09 16:53:58.041 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/Shrek the Third (2007)/
2022-02-09 16:53:58.519 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/The Bye Bye Man (2017)/
2022-02-09 16:53:58.683 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/The Good Dinosaur (2015)/
2022-02-09 16:53:58.698 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/The Great Gatsby (2013)/

You need to check that path..why does it error?  Does the folder exist?  is there an strm file in the folder?  That's still a big problem right there.  Do those items happen to be the newly added items that fail?  That will do it.

**Comment by 123Venom** [comment]
> I like library as I have created my own trakt lists that automatically update to my parameters. So it changes daily, and I love an instant load up, I also know you're not a fan of Auramod, but I've used it for a while now, and enjoy it.

Also you do not need library integration for this.  If it's your own list it will already be available to you in `My Movies - Movie Lists`.  Then just make a widget to it with your skin that we know supports widgets.  The same is true for `Liked Lists`.  You can like say the popular 

https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc 

Then it will also appear in your `My Movies - Liked Lists` and again make a widget pointing at it.  Honestly I think you guys are making this more complicated and going about it wrong.  People tended to use strm library integration because they used Estuary skin that does NOT support widgets so they could not do the above I explained and were stuck with library integration.  If you are using a skin that supports widgets I can't think of a logical reason to be use strm means of playback.

**Comment by adamosborne83** [comment]
Because I am the most inpatient person going. Which I know doesn't go well with kodi. 
With Library Integration it just allows instant load up with all my widgets

**Comment by 123Venom** [comment]
> Yes, that were the films that were showing the errors, but once deleted, cleaned, then added the way I mentioned they play perfect.

I want you to allow the condition to occur again.  Then **I want you to check that path** and if an strm file exists.  It looks like it can't write or something gets hosed during the process.  You realized I've stated this to you from the start to check that path the error claims....you never said what you found before nor what the content of the strm file is.  I feel like I starting to sound like a broken record.  When the path is not accessible you need to investigate!!!!!!!

**Comment by 123Venom** [comment]
> Because I am the most inpatient person going. Which I know doesn't go well with kodi. With Library Integration it just allows instant load up with all my widgets

true that.  It would be faster yes because the meta would then be local vs. requests to fetch it.

**Comment by adamosborne83** [comment]
> > Yes, that were the films that were showing the errors, but once deleted, cleaned, then added the way I mentioned they play perfect.
> 
> I want you to allow the condition to occur again. Then **I want you to check that path** and if an strm file exists. It looks like it can't write or something gets hosed during the process. You realized I've stated this to you from the start to check that path the error claims....you never said what you found before nor what the content of the strm file is. I feel like I starting to sound like a broken record. When the path is not accessible you need to investigate!!!!!!!

I have recorded a 5 min video that shows from start to finish. 
The strm file is fine and shows all meta and info etc.

**Comment by adamosborne83** [comment]
Also, I love this set up now.
Thanks to you haha
https://imgur.com/a/4HVClre

**Comment by 123Venom** [comment]
> I have recorded a 5 min video that shows from start to finish.
> The strm file is fine and shows all meta and info etc. https://imgur.com/a/8B4jE7L

in your video you showed you can access the drive but then you scrolled through the list so fast what good was that?.  You need to find the folder of the failing item and check the content of that folder.  You never showed the failing item in your video.  AGAIN...I ALSO WANT TO SEE THE CONTENT OF THE STRM FILE!!!!!!!  There's a reason Kodi is reporting...

ex....
`2022-02-09 16:53:55.023 T:4514    ERROR <general>: GetDirectory - Error getting /storage/19A5-1819/Android/data/org.xbmc.kodi/movies/Austin Powers International Man of Mystery (1997)/`

That is not Venom reporting that error.

**Comment by 123Venom** [comment]
Where's my venom.log?  Making me videos is for the most part useless...less you actually tried to view a failing path condition but not so.

**Comment by 123Venom** [comment]
> when you say the strm file, do you mean what it shows in the folder?
yes.  the .strm is a file inside the movie folder.  It has a one line entry in the file that initiates playback.  I need to see that the file exists and what is in it.  There's something going wrong with the folder or file.  I do set the path to write and create that strm file.  Kodi then adds an entry to it's db for it yet Kodi reports an error accessing it.

> I will enable venom log.
And make sure it is in `debug` mode.  There's a setting right below where you enable it in Venom's settings for the mode, either `normal` or `debug`.  You might as well do a run with Kodi in debug logging mode as well.  We should been at that point long time ago but you've not been hearing me.

**Comment by adamosborne83** [comment]
> > when you say the strm file, do you mean what it shows in the folder?
> 
> yes. the .strm is a file inside the movie folder. It has a one line entry in the file that initiates playback. I need to see that the file exists and what is in it. There's something going wrong with the folder or file. I do set the path to write and create that strm file. Kodi then adds an entry to it's db for it yet Kodi reports an error accessing it.
> 
> > I will enable venom log.
> 
> And make sure it is in `debug` mode. There's a setting right below where you enable it in Venom's settings for the mode, either `normal` or `debug`. You might as well do a run with Kodi in debug logging mode as well. We should been at that point long time ago but you've not been hearing me.

So this is me going into Hot Fuzz

https://imgur.com/a/fF5Hhl3


ALSO I pray this is the right log......

Https://paste kodi.tv/yamazuwaqu

**Comment by 123Venom** [comment]
ok...do not delete that Hot Fuzz folder/file!!  We need to examine that and we're getting close.

`ERROR <general>: CVideoPlayer::OpenInputStream - error opening [/storage/19A5-1819/Android/data/org.xbmc.kodi/movies/Hot Fuzz (2007)/?action=play_Item&title=Hot+Fuzz&year=2007&imdb=tt0425112&tmdb=4638]`

Now when I look at that line something looks wrong.  I still have that **Hannibal** movie I added to my library so I open the strm file and see this...

`plugin://plugin.video.venom/?action=play_Item&title=Hannibal&year=2001&imdb=tt0212985&tmdb=9740`

Yours appears to be this

`?action=play_Item&title=Hot+Fuzz&year=2007&imdb=tt0425112&tmdb=4638`

See what's missing there?  The plugin path and that's put there by `argv`..long story but not your problem.
but to confirm it I'd still like you to open that strm file and paste the content in here to confirm it, just like the line I pasted in here..  You'd have to access it from a file browse or pop that usb stick into a computer and navigate to that **Hot Fuzz** folder.  I'm not sure why new items added would have the plugin path but updated items added the path gets dropped?  Just sounds odd being the code I believe is the same to create the strm file.  I'll check that.  In the mean time confirm that file content for me please.

**Comment by adamosborne83** [comment]
> ok...do not delete that Hot Fuzz folder/file!! We need to examine that and we're getting close.
> 
> `ERROR <general>: CVideoPlayer::OpenInputStream - error opening [/storage/19A5-1819/Android/data/org.xbmc.kodi/movies/Hot Fuzz (2007)/?action=play_Item&title=Hot+Fuzz&year=2007&imdb=tt0425112&tmdb=4638]`
> 
> Now when I look at that line something looks wrong. I still have that **Hannibal** movie I added to my library so I open the strm file and see this...
> 
> `plugin://plugin.video.venom/?action=play_Item&title=Hannibal&year=2001&imdb=tt0212985&tmdb=9740`
> 
> Yours appears to be this
> 
> `?action=play_Item&title=Hot+Fuzz&year=2007&imdb=tt0425112&tmdb=4638`
> 
> See what's missing there? The plugin path and that's put there by `argv`..long story but not your problem. but to confirm it I'd still like you to open that strm file and paste the content in here to confirm it, just like the line I pasted in here.. You'd have to access it from a file browse or pop that usb stick into a computer and navigate to that **Hot Fuzz** folder. I'm not sure why new items added would have the plugin path but updated items added the path gets dropped? Just sounds odd being the code I believe is the same to create the strm file. I'll check that. In the mean time confirm that file content for me please.

Cannot thank you enough for taking the time to investigate this issue for me. I am away for the next few days, so i will give you the info you asked for when i return.
Although the gent, in my other issues has provided some logs too, if only i as as good as him.

Seriously thank you for spending your free time to maintain this free app.

**Comment by 123Venom** [comment]
This is getting a bit confusing.  You created a new issue to the same exact case and now we're exchanging comments in both issues.  Please refrain from this in the future.  I'll now only comment in this issue
https://github.com/123Venom/plugin.video.venom/issues/169
