### ISSUE TITLE
Some small bugs in the "Play Next" feature.

### ISSUE THREAD

**Issue by TapMeDead** [123Venom/plugin.video.venom#171]
I have just joined, so I don't know if these bugs have been reported or not.
(windows 10, Kodi 19.3, PC version, Venom updated to latest version)

1) Play Next will only work if you initiate it by actually left-clicking an episode link. If you do anything else, like scrape with source select, or use autoplay after right clicking, it doesn't get initiated.

2) When you are watching, using Play Next, as you get into further episodes and you interrupt the playback in the middle of, say, 2nd or 3rd or 4th episode you watched in a row, -then Play Next will save your resume point on the FIRST episode you started watching. No matter how many episodes you have watched via Play Next. Always saves resume point to the initial episode.

3) There is also a random error happening if you pause playback. Even if you are just 50% into the episode, if it hangs while reconnecting to the server to continue playback, it can set the whole episode as watched and skip to next episode. Leaving you no trace of how far you got into the episode it made the error on.
This error has happened three times for me, every time it was very near half way (50%) into the episode as i paused it.

**Comment by 123Venom** [comment]
This is rough as I'm a bit overloaded atm.  

Item 1.  There is a help file in the settings below `Enable PlayNext popup`.  Give that a good read.  That discusses setup.  I have it setup such that I just hit enter when viewing an episode list and continual playback works fine.  It's current functionality is not going to be enhanced further.  Using source select will always interrupt continual playback and I'm one dev that is against making it so you can select the source in between each and every episode, sorry I won't implement any such feature.  IMO that defeats the purpose of continual playback like a Netflix experience and I won't alter that.  Seren does this in the manner you mention and you might want to try that.  

Item 2.  That very well sounds like a bug and I may not be passing the current playing episode info for the resume point being saved.  I'll look into that one and fixing it.

Item 3.  I've seen this before myself, rare but I have seen it.  Unfortunately when a break in the connection occurs like that I'm not so sure there's much I can do as Kodi ends up falsely thinking the video finished.  I'll poke around about it however.

**Comment by TapMeDead** [comment]
@123Venom 
Thanks for the reply.
As for item no. 1, I am not asking to be able to pick between episodes. I am merely pointing out that if you do not initiate Play Next by actually (and only) clicking the episode like you would without play next, to start looking for servers, Play Next does not get initiated and playback stops after that episode. :)
I too have it so I can just hit 'enter' and the 'T' real quick to go to next ep and enable subs.

Might I add, I love your addon and features. I am disabled, and so I actually watch movies and shows at least 12 hours every day. :) I consider myself quite the expert in spotting issues, if one can say this without sounding like a jerk hehe.

**Comment by 123Venom** [comment]
Maybe I'm not following your item #1 then.  Left click/enter initiates continual playback and that method is all I ever intended for an uninterrupted continual playback method.

Your fine..I'm honestly getting burnt out.  Been at this all day answer people..altering code of other users I'm dealing with and feel like I'm exhausting myself.

**Comment by TapMeDead** [comment]
It's alright bro', these were just meant as bug reports really. Something you might or might not want to look at when you have time. Thank you so much for answering even when you are burnt out man. Get some rest, do not reply again hehe. Can delete issue if you want.
Regards Mike, Denmark.

**Comment by 123Venom** [comment]
no worries man.  Item #1 though.  Was I following you properly?  You were expecting continual playback in other methods than just left click/enter?  If so that was by design and how I honestly prefer it myself.

**Comment by TapMeDead** [comment]
Yep that's it :) Just a minor thing really. and if it is intended to work like that that's fine too :)
Be well :)

**Comment by 123Venom** [comment]
I've had requests to change that and just can't wrap my head around the point in it..lol.  I know Seren does allow it.

**Comment by TapMeDead** [comment]
Well, I edited one of my replys to include the why :)
Once in a while a bad file is auto selected when you start watching, and then you want to go back and use "source select" in some form or other, and by then, Play Next will not work. That's all :)

**Comment by 123Venom** [comment]
ahh yes..that is a valid point for it and I have seen that case and forces you to use source select.  If it happens if you could screen shot the source that caused it I like looking at that case and sometimes allows me to enhance FenomScrapers if possible to identify the issue.

**Comment by TapMeDead** [comment]
Yep, now that I know where to post such things, I will do that in the future if/when it happens.
Thank you again, a pleasure to talk to you.
Should you ever need help, as I said, I have time on hand, every single day :)

**Comment by 123Venom** [comment]
check your FB messages..lol
