### ISSUE TITLE
Trakt resume play not working

### ISSUE THREAD

**Issue by jpcaba** [123Venom/plugin.video.venom#172]
Operating System: Android
Device: samsung note 10+5g, FireTV, chromecast with google tv
Version of Kodi: 19.3
Version of Venom add-on: 6.4.9
Country: USA
Debrid services in use: Real-Debrid

I have the setting to have venom scrobble through trakt and resume set to trakt. It does not scrobble and it does not resume. I have also added the trakt app to scrobble but it does not resume. I also set the scrobble off in venom and resume trakt because of the trakt app was added and it still did not work. 

Let me know if you need more info. 

Thank you!

**Comment by TapMeDead** [comment]
I had this issue happen to me while watching Dodger. Checked the log file and to me looks like a Trakt error, like that show isn't registered right there. Your errors also with that show maybe?

**Comment by jpcaba** [comment]
Thank you for your response. I updated venom yesterday from version 4.something to 6.4.9 and it stopped working. It is also all shows.

**Comment by 123Venom** [comment]
I duplicated the issue with the show Dodger but the break is Trakt returns `tt` as an ID and not `tt11958674`.  It's been reported to them to fix.  As far as this issue happening with ALL shows...that I can not duplicate.  Try clearing cache and metadata

**Comment by jpcaba** [comment]
I have tried with Power Book II Ghost and with Star Trek Voyager. I have tried clearing all cache and it still does not work.

**Comment by TapMeDead** [comment]
I just tried with episodes 1 and 2 of Star Trek Voyager, and it sent ep 1 watched, and resume point on ep 2 as it should.
Must be a setting or something wrong at your end jpcaba.
Not a coder so I couldn't tell you what heh

**Comment by jpcaba** [comment]
I am not sure if this helps or not but when I stop a show in venom it says scrobble to local database. Also, I have exodus as a backup and I tested there. There the settings are set to enable scribbling to disabled state bit resume point to trakt. The trakt app is updating the scrobble and it is resuming on another device. It does not resume in venom.

**Comment by jpcaba** [comment]
I noticed with venom that if I disable scribbling it will revert the resume point source to local and bot trakt. I have tried removing the trakt app and enabling it and it does not help. 

@TapMeDead can you share your trakt settings info with me?

**Comment by saxoloman** [comment]
I have same problem,but sometimes resume is possible untill i leave to main menu of venom.when i get back resume is no longer available...

**Comment by jpcaba** [comment]
I have that turned on. Are you suggesting turning it off?

**Comment by TapMeDead** [comment]
I have mine on.
I reinstalled Kodi and Venom just a few days ago. I had some errors the dev couldn't duplicate. And since I did that everything works. Right now I only have Venom in this Kodi. And it works with the PlayNext enabled. Love it :)

**Comment by TapMeDead** [comment]
I also have the 6.4.9 update running as is.

**Comment by TapMeDead** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/99356645/153972532-48da58d3-56c7-4d21-86f9-d9c0c39b8f81.png)

This is how my trakt settings look for scrobble, and without the trakt addon installed

**Comment by jpcaba** [comment]
That's exactly how I have it. Do you also have the trakt app in program addons?

**Comment by TapMeDead** [comment]
It does show Trakt in program addons. But i didn't install it, that must be a dependency from Venom.

**Comment by jpcaba** [comment]
I'm going crazy with this. I've removed the trakt addon as I installed it myself. It still does not work. Only when I disable scribbling and it uses the local database.

**Comment by 123Venom** [comment]
how about posting the logs?  venom.log in debug mode should shed some light on it...but make sure Trakt scrobble is enabled and the resume point source is also set to use it...then run a case of just manually marking as watched should have something in the log what happened.

@TapMeDead and I spent about 3 days testing before releasing that version and it was fine.  Since your post the only show having an issue was **Dodger** but that's a trakt issue.

**Comment by TapMeDead** [comment]
The only setting I can think of that needs to be set after installing Venom, to make PlayNext work, is this one, in Player Setting, little arrow points at it
![Screenshot_2](https://user-images.githubusercontent.com/99356645/153974342-debc670a-8f0f-4510-86ef-41410d0fea9e.png)
.

**Comment by jpcaba** [comment]
I dont use the PlayNext setting.

**Comment by 123Venom** [comment]
That setting is only needed if one want to use continual playback of Episodes and not have to use **Play from here**.  The setting should have no effect on Trakt scrobble/resume points being created or not.  Having the Trakt addon scrobble while Venom also tries to post a scrobble might cause an issue and user should use one or the other...never both.

**Comment by jpcaba** [comment]
Thank you. I have used both in prior versions with no issue. I have also used the trakt addon only and I have only used venom to scrobble only and none of those are working for me.

**Comment by 123Venom** [comment]
So I just disabled PlayNext in source select mode.  I played S01E01 of Peacemaker.  I seeked to 50% and waited about 5secs to make sure Kodi recognixed the playing position.  Upon stopping the video i'm still getting the Trakt scobble notice and the resume indicator was then shown upon the container.refresh.  Even trying to match your settings I can not duplicate the condition.  There might be something else triggering it but I'm stumped what that is.  Manually marking watched/unwatched was still working fine also.

**Comment by jpcaba** [comment]
I see an error in the log. I have attached it. 
![20220214_202651](https://user-images.githubusercontent.com/99694885/153975149-880747a1-e94f-498e-b08c-60710045d038.jpg)
![20220214_202704](https://user-images.githubusercontent.com/99694885/153975166-7571053e-4e76-489b-972f-cf96883d0935.jpg)

**Comment by xyzfre** [comment]
I'm on the latest version of venom and I actually feel like Trakt is working better in every way and my progress works perfectly when I stop a show or movie ,, just gave it a test run in many ways and also cannot duplicate this issue

**Comment by 123Venom** [comment]
try **Force Trakt Sync to local database**.  It's under **Tools - Trakt Management Tools**.  The db may have become malformed.

**Comment by 123Venom** [comment]
The created table is suppose to have 13 columns.  I'm reading and writing to 13.  If your table only has 7 something got hosed and that's the issue right there!!!  Hopefully forcing a new sync should rebuild that **bookmarks** table

**Comment by jpcaba** [comment]
I have tried that before. I will try again. Last resort will be to Uninstaller venom and reinstall it.

**Comment by 123Venom** [comment]
For example...here's my **bookmarks** table.  There's 13 columns of data.

<img width="1043" alt="bookmarks_table" src="https://user-images.githubusercontent.com/46383815/153977251-108781c0-031e-409d-a1a4-f7e1307255af.PNG">

I'd be curious to see yours but you'd have to really know what you're doing to view it.  The re-sync should rebuild it to have 13.

**Comment by 123Venom** [comment]
and for the record...**Peacemaker** is first item in that table because that was a test case to verify it works fine for me here.  The date created is in UTC because that's how trakt keeps it's records

**Comment by jpcaba** [comment]
So the force did not work. However, I Uninstaller and reinstalled venom and it worked.

**Comment by jpcaba** [comment]
Thank you all for your time and help. Truly appreciate it.

**Comment by 123Venom** [comment]
lol..I was hopeful you'd first respond with how the force trakt sync worked out because I'm thinking I spot an issue where the forced condition re-writes new data to the existing table...meaning it does not look like I wipe out the table so in the event a table was previously malformed like yours, 7 columns vs. 13, a table wipe would start over from nothing and make the required 13 columns fresh from scratch.  If I do not wipe the table then it will attempt a 13 column write still to 7 columns and fail.  Ohh well to late to further diagnose since you re-installed...that absolutely started you fresh so your table now I'm 100% sure has 13 columns.

There does look like a slight issue I need to address as a fallback in the event a table became corrupt a wipe of the table when forcing a sync will fix it.  I'll address that for next update.

**Comment by jpcaba** [comment]
I still have other devices that have this issue. I can hold off on Uninstaller if you'd like? I have 2 more devices available.

**Comment by 123Venom** [comment]
ohh sweet.  I just dialed in a code change to make that **Force Trakt Sync to local database** wipe out the tables and start fresh.  That way as a good fallback means if a table became previously corrupt, like your case, it will not just rebuild new data but wipe out the table first and then start the rebuild process from scratch..making a new column layout for each.  Previously it just re-wrote all new data to the expected column layout and in most cases that's fine but in the event like yours and one table became corrupt it would not fix it. Soooo..here's what I'd like you to do.  Lets verify the force sync doesn't work on the other device, I suspect it will not.  Then I'll make a zip of this new code change that wipes out the tables...then install and restest a new force sync again and it should cure it

So you have other devices with this same table column error?  Damn that's really strange

**Comment by jpcaba** [comment]
I do. I backup my builds and restore to multiple devices. It's my TV. So each room in the house has a kodi app. 

I think because I went from version 4 to the latest, it caused thus corruption? Maybe. 

I just tried the force and it did not fix it.

**Comment by 123Venom** [comment]
ok..sit tight..don't touch the failing device, we need that guy..lol.  I'll upload a zip for you to test and all you do is repeat the forced sync and test if it fixed it.  I'm just now wiping out all tables is the difference.  I ran a quick test to make sure my own db was put right on back and things looked good so we need a device that fucked and you're it..lol

I'll post a link for the test zip in a few..brb

**Comment by jpcaba** [comment]
Lol. Sounds good.

**Comment by 123Venom** [comment]
https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.9.1.zip

Give that a whirl and just repeat the process of a forced sync and retest it.  Fingers crossed but that should wipe it out and start fresh.  Let me know.  Ohh also you know when you install from zip that once I push an official version AutoUpdates will not work right?  That's a Matrix change they did.  If you have update notification on you'll see the notice and then install from repo and you'll be back on AutoUpdates

**Comment by jpcaba** [comment]
I am trying to install it but it keeps getting stuck at imstalling 77%. I downloaded the zip and put it on a share drive on my home network, then click on install from zip file, then find the zip on share drive. Is there a better way to do this?

**Comment by 123Venom** [comment]
hold on..something seems off.  I just checked the contents of that zip and the trakt module I updated is old file...SOB...prob flying to damn fast here and gaffed it.  Let me recreate it and try again.  Delete that zip file because even if installed it's not right and has the original file and not the one I modified for some odd reason so you'd not see a change on it.

**Comment by jpcaba** [comment]
Ok. Deleted.

**Comment by 123Venom** [comment]
https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.9.2.zip

yep..my bad.  I actually already had a 6.4.9.1 test zip so the repo gen tool saw that and did not create a new one...I needed a version `.2` bump.  Sorry dumb gaff rushing and not looking.  This now has the right trakt module change for the database issue.  That may not have anything to do with your stuck 77% issue but at least I now know you have the right zip file.

**Comment by TapMeDead** [comment]
I just installed same update zip for a test. I had it on a local drive though. Network drives and Kodi has in the past shown issues.

**Comment by jpcaba** [comment]
Ok. Got it to update. Trying it now.

**Comment by jpcaba** [comment]
Yeah. I just moved the zip to the local file store of the device and that
worked.

**Comment by 123Venom** [comment]
worked install wise or did it also cure the database table issue?  Did you test that part of it?

**Comment by jpcaba** [comment]
All of it works. It cured the database issue. And it installed correctly. Also made sure it resumed on another device and it did.

**Comment by 123Venom** [comment]
Nice!!!  That fallback condition will be included then in next release.

**Comment by jpcaba** [comment]
Thank you all for everything. You guys are awesome. Family is happy!
