### ISSUE TITLE
High resolution images for TV and movie info?

### ISSUE THREAD

**Issue by Madddcow** [123Venom/plugin.video.venom#175]
Hi there.  Am I missing something or is there no way to enable high resolution images for TV shows and movie info e.g. cast images etc? I've been able to configure this in Seren but am also hoping to do this in Venom. I've added my Fanart API to Venom's accounts and enabled extended artwork etc but am still getting grainy cast images for TV shows and movies.

**Comment by 123Venom** [comment]
yep..the cast images I chose a lower res because the menu load time is much faster on the smaller file size and I cared more about that.  I may consider an option to set the images res. but keep that in mind if I do the impact increasing the res will have.

**Comment by 123Venom** [comment]
I added an adjustment for this in next update so you will be able to chose from `low, medium, high, and original`

**Comment by Madddcow** [comment]
Thanks so much....really, really appreciated!
