### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#176]
Hi Mr Venom, hope you're well.

This might be auramod, as I know you're opinion of the skin, but when I click to watch a movie, kodi crashes repeatedly. 

https://paste.kodi.tv/onivuzulul

**Comment by 123Venom** [comment]
I just gave AM a quick test on my pc and could not reproduce this trying to initiate playback using a library strm file.  I also tried to use the CM item `TMDbHelper Options` to select the Venom player and still was fine.

I did spot in your log after playback being initiated.
`
INFO <general>: [ plugin.video.venom ] onAVStarted callback
` 
This error occurs....
```
2022-03-13 10:03:12.718 T:13717   ERROR <general>: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
2022-03-13 10:03:12.718 T:13717 WARNING <general>: CCurlFile::FillBuffer - Reconnect, (re)try 1
2022-03-13 10:03:12.755 T:13717   ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2022-03-13 10:03:12.755 T:13717 WARNING <general>: CCurlFile::FillBuffer - Reconnect, (re)try 2
2022-03-13 10:03:12.757 T:13717   ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2022-03-13 10:03:12.757 T:13717   ERROR <general>: CFileCache::Process - <https://51.download.real-debrid.com/d/WISSJFY67J6F4/Big%20Trouble%20in%20Little%20China%201986%20BluRay%201080p%20DTS%20dxva%20LoNeWolf.mkv> source read didn't return any data before eof!
```

metadatautils then also goes ape shit with errors.

Honestly looks to me like connection problems beyond anything I can do something about.

When you see this `[ plugin.video.venom ] onAVStarted callback` that's Kodi making a callback to the addon that playback was initiated and at that point the addons job is done.

I did spot another attempted playback and see this

```
2022-03-13 10:05:29.204 T:16022   ERROR <general>: CFileCache::Process - <https://62.download.real-debrid.com/d/5D2IZ4TQOU3VY/Run.All.Night.2015.2160p.HDR.WEBRip.DTS-HD.MA.7.1.EN.FR.x265-GASMASK.mkv> source read didn't return any data before eof!
2022-03-13 10:05:29.420 T:15999    INFO <general>: [ plugin.video.venom ] onAVStarted callback.  In Venom I log all callbacks made by Kodi to the addon to assist in tracing issues.
```

This one strikes me odd.  Here Kodi detects that no data was received before `eof`(End Of File) yet it still then made a callback to the addon that playback began...lol.  That imo is a failed means to handle the condition by Kodi and SHOULD NOT be making that callback on a failure but instead it should be making the `onPlayBackError()` callback but does not.

That second attempted playback looks like a failed cached torrent on RD to me and handled poorly by Kodi but should should not have caused a crash...then again metadatautils did again go ape shit with errors.

**Comment by 123Venom** [comment]
I also found it odd that I could not turn up this cached torrent from RD...
```Run.All.Night.2015.2160p.HDR.WEBRip.DTS-HD.MA.7.1.EN.FR.x265-GASMASK.mkv```
Then I peaked at the uncached torrents list and found it....
<img width="1373" alt="uncached torrent" src="https://user-images.githubusercontent.com/46383815/158075708-cd5f0bd8-4dd7-45ee-bf54-050da82c701b.PNG">

I've had it happen to me a few weeks ago a failed to resolve case and then when I studied it closer from the time it was cache checked till the time I hit enter on the cached torrent someone removed it and was no longer cached.  It's very rare that will happen within a small maybe 10sec window of time but it's happened to me.  That looks to be the case with that torrent as it's no longer cached.

**Comment by adamosborne83** [comment]
> I just gave AM a quick test on my pc and could not reproduce this trying to initiate playback using a library strm file. I also tried to use the CM item `TMDbHelper Options` to select the Venom player and still was fine.
> 
> I did spot in your log after playback being initiated. `INFO <general>: [ plugin.video.venom ] onAVStarted callback` This error occurs....
> 
> ```
> 2022-03-13 10:03:12.718 T:13717   ERROR <general>: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
> 2022-03-13 10:03:12.718 T:13717 WARNING <general>: CCurlFile::FillBuffer - Reconnect, (re)try 1
> 2022-03-13 10:03:12.755 T:13717   ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
> 2022-03-13 10:03:12.755 T:13717 WARNING <general>: CCurlFile::FillBuffer - Reconnect, (re)try 2
> 2022-03-13 10:03:12.757 T:13717   ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
> 2022-03-13 10:03:12.757 T:13717   ERROR <general>: CFileCache::Process - <https://51.download.real-debrid.com/d/WISSJFY67J6F4/Big%20Trouble%20in%20Little%20China%201986%20BluRay%201080p%20DTS%20dxva%20LoNeWolf.mkv> source read didn't return any data before eof!
> ```
> 
> metadatautils then also goes ape shit with errors.
> 
> Honestly looks to me like connection problems beyond anything I can do something about.
> 
> When you see this `[ plugin.video.venom ] onAVStarted callback` that's Kodi making a callback to the addon that playback was initiated and at that point the addons job is done.
> 
> I did spot another attempted playback and see this
> 
> ```
> 2022-03-13 10:05:29.204 T:16022   ERROR <general>: CFileCache::Process - <https://62.download.real-debrid.com/d/5D2IZ4TQOU3VY/Run.All.Night.2015.2160p.HDR.WEBRip.DTS-HD.MA.7.1.EN.FR.x265-GASMASK.mkv> source read didn't return any data before eof!
> 2022-03-13 10:05:29.420 T:15999    INFO <general>: [ plugin.video.venom ] onAVStarted callback.  In Venom I log all callbacks made by Kodi to the addon to assist in tracing issues.
> ```
> 
> This one strikes me odd. Here Kodi detects that no data was received before `eof`(End Of File) yet it still then made a callback to the addon that playback began...lol. That imo is a failed means to handle the condition by Kodi and SHOULD NOT be making that callback on a failure but instead it should be making the `onPlayBackError()` callback but does not.
> 
> That second attempted playback looks like a failed cached torrent on RD to me and handled poorly by Kodi but should should not have caused a crash...then again metadatautils did again go ape shit with errors.

Cheers as always for your reply, this is not going to be related to your app, but I think its something to do with my surround sound set up, as I use firecube and then 2 amazon studios wirelessly to create my surround sound. 

https://imgur.com/a/M5KrKBQ
Alot of sound errors.

**Comment by 123Venom** [comment]
both cases look to me like either connect issues or they're both ending with `source read didn't return any data before eof!` and the magnet/torrent is no longer cached.  Try clearing providers and starting fresh.  Maybe your cached source links is old but it should only be held for 24hrs but if someone removed the item in that time frame I can see it throwing that error.  Nature of the best but again it shouldn't cause crashes that I can't reproduce.  What's going on with metadatautils is something you may want to look into.

**Comment by adamosborne83** [comment]
> both cases look to me like either connect issues or they're both ending with `source read didn't return any data before eof!` and the magnet/torrent is no longer cached. Try clearing providers and starting fresh. Maybe your cached source links is old but it should only be held for 24hrs but if someone removed the item in that time frame I can see it throwing that error. Nature of the best but again it shouldn't cause crashes that I can't reproduce. What's going on with metadatautils is something you may want to look into.

OK, well thanks for the info, it's happened on loads of movies......  
I think I've posted about 10 different logs today, just don't understand it.
But, obviously not a Venom issue.

https://paste.kodi.tv/morohugihe

https://paste.kodi.tv/tecirexabu

https://paste.kodi.tv/pakuqigayo

https://paste.kodi.tv/axonunobut

Feel free to close this issue.

Guess this is one of those horrible things, just don't get why all of a sudden lol

**Comment by 123Venom** [comment]
I'm confused.  Why did you just try playing the same file I showed you is no longer cached on RD?

```
2022-03-13 15:50:34.425 T:21503   ERROR <general>: CFileCache::Process - <https://52.download.real-debrid.com/d/O4DECBNUOARH6/Run.All.Night.2015.2160p.HDR.WEBRip.DTS-HD.MA.7.1.EN.FR.x265-GASMASK.mkv> source read didn't return any data before eof!!
```

In each of the failed cases from RD I saw it was the same and they're prob no longer cached.

**Comment by adamosborne83** [comment]
> I'm confused. Why did you just try playing the same file I showed you is no longer cached on RD?
> 
> ```
> 2022-03-13 15:50:34.425 T:21503   ERROR <general>: CFileCache::Process - <https://52.download.real-debrid.com/d/O4DECBNUOARH6/Run.All.Night.2015.2160p.HDR.WEBRip.DTS-HD.MA.7.1.EN.FR.x265-GASMASK.mkv> source read didn't return any data before eof!!
> ```
> 
> In each of the failed cases from RD I saw it was the same and they're prob no longer cached.

Hey, just to let you know I figured a fix around this.
As you'd mentioned it stated end of file, but found it odd that happened to a lot of movies. Anyway, I was playing with my setting and I had terminate on cloud source unticked. 
Bit, as it was in my RD downloads, so therefore was downloading etc, I ticked it, and for last 2 days on all movies it now works. 
I know I'm unique, as cannot see anyone ever having this issue, but just thought I'd let you know. 
You're fantastic support as always.

**Comment by 123Venom** [comment]
I don't know why on earth that would have anything to do with it.  The `Terminate on cloud source` stops a scrape early when it finds the item in your cloud.  That is before you even select a source to be resolved for playback.  The resolve is working properly and playback is initiated with the resolved file.  You're problem was that resolved file RD was not responding back with data and why the `eof` error happened.  That has nothing to do with Terminating on cloud sources, only effects the scrape for sources.  I think it's coincidence and maybe for a spell you were really suffering from RD server problems that's now resolved.

**Comment by adamosborne83** [comment]
> I don't know why on earth that would have anything to do with it. The `Terminate on cloud source` stops a scrape early when it finds the item in your cloud. That is before you even select a source to be resolved for playback. The resolve is working properly and playback is initiated with the resolved file. You're problem was that resolved file RD was not responding back with data and why the `eof` error happened. That has nothing to do with Terminating on cloud sources, only effects the scrape for sources. I think it's coincidence and maybe for a spell you were really suffering from RD server problems that's now resolved.

Haha, how correct you were, had problems all day today and I even trued on a different RD account too, might give PM a go and hope that fixes it.... again, thabk you and hope you're well.
