### ISSUE TITLE
[Feature Request/Issue] Continuous Trakt Scrobble

### ISSUE THREAD

**Issue by HashaRock** [123Venom/plugin.video.venom#177]
I have been testing out a couple of different addons over this week and golly this one takes the cake by far. It is extraordinarily fast and the menus load way quicker than alternatives. Trakt Scrobble also works perfectly but I have one small complaint. On my device (Hisense U7G, Android TV, Kodi 19.0 DV Edition), Trakt scrobbles my last known position and saves that to the Trakt API (seen by TPPM Sharkykh). However, it doesn't have the **continuous** scrobbling where TPPM says that I am currently watching. 

So, Is this an issue on my side or a setting that needs to be unlocked or can this be added in the future? Brilliant addon Mr. Eddie Brock and thank you for your time and effort in making this!

**Comment by 123Venom** [comment]
I believe what you describe is accomplished by sending to trakt api the scrobble start and stop where I only send the pause as a percent when playback is stopped by the user.  What I'm currently doing would not allow it to be seen by TPPM as currently watching.  Not sure I wish to re-code that either.

**Comment by HashaRock** [comment]
This makes perfect sense. Since I usually don't always press the stop button on the OSD and just pause it, I want to make sure the progress gets saved. Thanks for the response!

**Comment by 123Venom** [comment]
When you hit pause only as you say then how are you then browsing anything with the player sitting in pause mod?  If I've lost interest in what I'm watching I always just hit stop and if the watched percentage is in the range to make a resume point it does.

**Comment by HashaRock** [comment]
Usually if I need to switch devices, I simply pause to move to another device and if I come back, I stop and then resume. Usually this is because I don't want to reselect the file I chose for the TV vs a mobile or laptop device.
