### ISSUE TITLE
Scraping: Torrents

### ISSUE THREAD

**Issue by ronfrankhill** [123Venom/plugin.video.venom#178]
This add-on managed to find links very fast for old and new episodes that might be over 5 years etc in a very short period with the use of RD in good quality for 1080p. Thanks.

**Comment by xyzfre** [comment]
Venom is definitely an amazing add-on mad respect✊🏼to the dev for his GREAT work👏🏼👏🏼 and thank you for sharing it with us users

**Comment by 123Venom** [comment]
Thank you for the kind words
