### ISSUE TITLE
TV Shows - Progress

### ISSUE THREAD

**Issue by heimdall47** [123Venom/plugin.video.venom#179]
I have setup 'Progress' in My TV Shows as a widget in the Auramod skin. When I try to play the next episode shown in the Progress widget it goes to the Play screen. After clicking play it says please wait and then it comes to a standstill. I have tried clearing the cache and reauthenticating trakt in 'My Accounts' but even this does not work. Attaching the kodi.log and venom.log. Also a few pictures. Please fix this issue
[kodi.log](https://github.com/123Venom/plugin.video.venom/files/8325813/kodi.log)
[venom.log](https://github.com/123Venom/plugin.video.venom/files/8325814/venom.log)
![20220322_193138](https://user-images.githubusercontent.com/50041938/159521011-87b23898-ee6c-4cd8-a261-9c5bfc92f9fb.jpg)
![20220322_193159](https://user-images.githubusercontent.com/50041938/159521056-3f13dd8e-572f-4490-bf48-06b490771749.jpg)
![20220322_193212 1](https://user-images.githubusercontent.com/50041938/159521085-a733f4c9-5b28-45c4-a5f0-1aac86744a3b.jpg)

**Comment by TapMeDead** [comment]
In settings/Trakt, you should enable "Direct Progress Scraping". This is not a bug, it's feature :)

**Comment by xyzfre** [comment]
> I have setup 'Progress' in My TV Shows as a widget in the Auramod skin. When I try to play the next episode shown in the Progress widget it goes to the Play screen. After clicking play it says please wait and then it comes to a standstill. I have tried clearing the cache and reauthenticating trakt in 'My Accounts' but even this does not work. Attaching the kodi.log and venom.log. Also a few pictures. Please fix this issue
> 
> [kodi.log](https://github.com/123Venom/plugin.video.venom/files/8325813/kodi.log)
> 
> [venom.log](https://github.com/123Venom/plugin.video.venom/files/8325814/venom.log)
> 
> ![20220322_193138](https://user-images.githubusercontent.com/50041938/159521011-87b23898-ee6c-4cd8-a261-9c5bfc92f9fb.jpg)
> 
> ![20220322_193159](https://user-images.githubusercontent.com/50041938/159521056-3f13dd8e-572f-4490-bf48-06b490771749.jpg)
> 
> ![20220322_193212 1](https://user-images.githubusercontent.com/50041938/159521085-a733f4c9-5b28-45c4-a5f0-1aac86744a3b.jpg)
> 
> 
> 
> 

Or you could disable that feature in skin settings,Home/ Media Types/ and uncheck episodes, I use AuraMOD and Venom I only leave Movies and TV shows enabled for Media Types
