### ISSUE TITLE
REQUEST: Would like the number to appear in the popup that is tied to the source it is trying to play

### ISSUE THREAD

**Issue by jpcaba** [123Venom/plugin.video.venom#183]
When choosing from the source select window, the popup tries to play the video from the source.  The title of the source is displayed but not the number.  So if the item it lands on is broken, it is hard to tell where the popup left off so that way I can go back to source select and skip that source and choose another one.

**Comment by TapMeDead** [comment]
@jpcaba It should just skip through broken links and start playback from a working one. I watch a lot, a LOT! of shows and movies, this is not a big issue really.

**Comment by 123Venom** [comment]
Unfortunately the number is not an assigned variable I pass back so it's not easily accessible for me to add that. It's possible I can do this by way of an index value but it's a bit of work.  I'll consider it.

**Comment by jpcaba** [comment]
@TapMeDead this is not an issue.  IT is a request.  I watch A LOT too!  The point I am making is that it would be beneficial to have the number next to the title so I can see where it left off.  Sometimes it is not broken but playing the wrong episode or the wrong year of the show (ie Magnum PI Original versus remake).  Its not just broken.  Sometimes it even says "One or more issues has occurred."  Surely someone with your calibor of "watching" tv show and movies would have seen some of these issues.

**Comment by jpcaba** [comment]
@123Venom, thank you!  I have seen it before in prior release.  Whatever you can do would be appreciated.

**Comment by jpcaba** [comment]
@123Venom  maybe append the number to the title?  That way you don't need to change the popup.

**Comment by 123Venom** [comment]
> @123Venom, thank you! I have seen it before in prior release. Whatever you can do would be appreciated.

that was long ago on the old directory style source select, completely different method now.

**Comment by 123Venom** [comment]
> @123Venom maybe append the number to the title? That way you don't need to change the popup.

That'd mess up the magnet title when trying to resolve...no can do that one.

**Comment by jpcaba** [comment]
Ahhh!  Gotcha!  Thanks.

**Comment by 123Venom** [comment]
I got an idea for this I'm toying with now.  I can get the index of the selected item and increment it as it attempts to resolve.

**Comment by 123Venom** [comment]
<img width="1242" alt="index_1" src="https://user-images.githubusercontent.com/46383815/162071246-fc724593-aa88-4f27-97e2-84f260c4bf63.PNG">
<img width="1073" alt="index_2" src="https://user-images.githubusercontent.com/46383815/162071251-954187bf-209b-47eb-a647-4853098e1595.PNG">

@jpcaba if I was to upload a modified module are you skilled enough to drop in in the folder I direct you to?  Or I could uplaod a zip file for an install but If I can get away from users doing that on Matrix I'd rather because it breaks AutoUpdates in Matrix now due to a change THEY made.

**Comment by jpcaba** [comment]
Yes I can help.  We worked the Trakt database issue together (from 7 columns to 13 columns issue).

**Comment by 123Venom** [comment]
https://github.com/123Venom/zips/tree/dev

`source.py` drop in the `modules` folder.  Make sure you jump out of Venom to another addon and back again...long story why you have to do that with a code change like this.

Test that.  I struggled to find a source that'd skip links on me....your turn..lol

**Comment by 123Venom** [comment]
GOT has some m2ts packs in Season1 and we can't resolve those suckers so I know they'll skip.  I just tested and it did skip the first 3 and the index counted fine.

**Comment by jpcaba** [comment]
Works beautifully!  I just tested with Castle.  It skipped the first one and played the second one.  Thank you, sir!

**Comment by 123Venom** [comment]
Check the venom.log and see if it captured why that Castle episode source got skipped.  I try to fix cases that are fixable but sometimes they're just not.

**Comment by 123Venom** [comment]
Like that GOT m2ts season pack...that can't be fixed.  Movies are easy to resolve as we just get the largest m2ts and it's the movie.  Season disks there's just no way to know ex. `0053.m2ts` is what episode? lol.  If there was a databse that cross referenced the disk we could but I've hunted and no such exists I found.

**Comment by jpcaba** [comment]
![image](https://user-images.githubusercontent.com/99694885/162083442-74da34f9-8de3-4381-890c-50c34300e7f0.png)

**Comment by 123Venom** [comment]
Something is strange there.  I see an S05 pack file but prior to that the failue is `The.Man.in.the.high.Castle` I assume since it's cut off.  I can't even find an episode of that title in Season5.  Can you snap of pick of the source select screen showing that link?

**Comment by 123Venom** [comment]
https://trakt.tv/shows/the-man-in-the-high-castle

Looks like a completely different show that should not be showing up.

**Comment by jpcaba** [comment]
![image](https://user-images.githubusercontent.com/99694885/162084981-7a8015c1-4a9b-4b2c-838d-144bcb5fb049.png)

**Comment by jpcaba** [comment]
I thought that sounded familiar.

**Comment by 123Venom** [comment]
yikes..that's nasty.  Something in BITCQ scraper is fucked.  I'll check.  I knew there's a reason for seeing `no matching season/episode found`.  It was looking inside that pack for `S05E07` but that suckers S01 of that other show.

**Comment by 123Venom** [comment]
yep..bug in BITCQ season packs...fixed and I uploaded a new version to....
https://github.com/123Venom/zips/tree/dev

Scratched my head over it at first and then it occurred to me BITCQ went offline for a few weeks and I had removed it.  During that time we added a new range method for packs to keep.  BITCQ came back online and I added it back in but forgot to add the new code it was missing that we added during it's down time...woopsie

Drop that into `addons\script.module.fenomscrapers\lib\fenomscrapers\sources_fenomscrapers\torrents` and rescrape that case.  I was getting that one cached source but also a whole bunch in the `uncached` list..all from BITCQ only.

**Comment by 123Venom** [comment]
That's a pretty bad gaff on my part so I'm prob going to push an update for it tonight

**Comment by jpcaba** [comment]
Thank you.

**Comment by jpcaba** [comment]
@123Venom the bitcq.py file worked.  That torrent did not come up in the list.

**Comment by 123Venom** [comment]
> Sometimes it is not broken but playing the wrong episode or the wrong year of the show (ie Magnum PI Original versus remake).

btw...there's a setting to require the year for known reboot shows.  That can help sometimes.

**Comment by jpcaba** [comment]
Thank you!!

**Comment by jpcaba** [comment]
Can we have the number also appear when using the playnext option? This is working when using source select but not auto play.

**Comment by 123Venom** [comment]
The PlaNext feature is intended to be an uninterrupted experience even with background scape and resolve process.  I'm not interested in chanting this functionality

**Comment by jpcaba** [comment]
Ok
