### ISSUE TITLE
REQUEST: Would like the next season displayed after I have completed watchin one season from the progress area

### ISSUE THREAD

**Issue by jpcaba** [123Venom/plugin.video.venom#184]
When loading a show from the progress screen, it will only show the episodes tied to the season I am in.  Once I finish that season, I have to go back to progress to get the next season.  It would be cool if the container refresh would load the next available season if one exists.  This way I do not have to go back to Progress to then play the next episode in the next season.

**Comment by TapMeDead** [comment]
@jpcaba Seems like a lot of coding to make that work. I am sure the dev himself might have a look at that, but might not be possible with the tools Kodi provides as it is.

**Comment by jpcaba** [comment]
I am sure there will be code changes needed.  He changed it to only load a season at a time in the Progress section.  At one point it would load all remaining episodes.  It would be a check to see if there is another season, if there is load the next season's episodes, if not, leave the list the way it is.

**Comment by 123Venom** [comment]
The time when it would load ALL remaining episodes was WAY back when I used TVDb as our meta source for shows.  We use TMDb now and they do not provide all episodes in the response like TVDb did so this is not really possible without a major amount of rework that I'm not sure I'm interested in doing.  You could maybe use `Flatten TV seasons`.

**Comment by 123Venom** [comment]
Looks like Flatten does not work on the Progress list

**Comment by jpcaba** [comment]
I understand.  Thank you for checking.

**Comment by 123Venom** [comment]
Truthfully if you want continual playback from season right into the next season Seren handles this much better.  It's just not an avenue I've cared enough about to venture into the time it would take me to re-write that all.

**Comment by jpcaba** [comment]
Thank you.  I am a big venom fan.  Not sure I want to use another addon. LOL

**Comment by 123Venom** [comment]
I put it in my notes though to see if I can come up with something.

**Comment by jpcaba** [comment]
Awesome. Thank you!

**Comment by 123Venom** [comment]
I think I have a solution.  What if I made the context menu option `Browse Series` respect the `Flatten TV Seasons`?  Or better yet maybe a new setting below that for `Flatten TV Series (only in Browse Series)`?

I just made it respect the current setting and using Browse Series now Flattens it so all eps show up using `Browse Series` from Progress
<img width="1187" alt="Flatten_browse series" src="https://user-images.githubusercontent.com/46383815/162093612-28347372-5a82-4b6f-a644-d1c7bfd62a3d.PNG">

Browse Series however does not load from your Progress/Next Up item to watch.  I might be able to transfer that starting episode over.  Also with `Direct Progress Scraping` off it loads the remaining episodes of that season so maybe I can pass that as a `flatten` option...still contemplating it.  Sometimes the problem becomes that so many things intertwine that one change breaks something else so you have to follow the full flow of code and how it all mates...common gaff we all make mistakes on and break something elsewhere we didn't think of.

**Comment by jpcaba** [comment]
sounds like a good idea.
