### ISSUE TITLE
ISSUE: Not showing all seasons of American Idol

### ISSUE THREAD

**Issue by klyco** [123Venom/plugin.video.venom#185]
Hi there,
First off, thanks SO much for this Add-on!

This may happen on other shows, but I only found it on American Idol so far...

The Seasons only go up to 15, when there are 20 seasons listed in The TVDB.

It is easily repeatable;  Search for American Idol and click on Browse.

I am using the latest Kodi 19.4 on Windows 11, with the latest Venom 6.5.5.

Cheers!
Ken

**Comment by 123Venom** [comment]
We don't index TVDb.  TMDb is our meta source.
https://www.themoviedb.org/tv/3626-american-idol

15 seasons listed.  You'd have to report the issue to them.
