### ISSUE TITLE
ISSUE: Not showing all seasons of American Idol (previously opened #185)

### ISSUE THREAD

**Issue by klyco** [123Venom/plugin.video.venom#186]
Hi!

So sorry to re-open this case, but I think I need a further chat.  Maybe you can merge these?

So, I spoke to TMDB and they said there are 2 shows (eyeroll) because Fox cancelled the show and then ABC picked it up...

So they have 2 entries for American Idol; one aired 2002 and the other aired 2018.

The new show (2018), up to date, has Seasons 1 - 5.

The problem is that all the streams out there continued on the naming convention, so they are up to Season 20 currently (i.e S20E01 etc).  Therefore, even though I can find the ne American Idol in the search, I can't find any streams.

Anyways, I know it is only a single show, and since nobody else in the world watches it, it is likely not high on your fix list lol.  And I'm not sure there would be an elegant way to even fix it.

I jut wanted to throw it out there in case this situation has happened before, and there may possibly be a fix for  it.

Cheers and thanks again for a wonderful addon!!
Ken

**Comment by 123Venom** [comment]
You can use a custom scrape to change the season and episode you're after.  Beyond that I can't fix meta mismatches with torrent uploads.  Pull up the **Rescrape Options--->** context menu options and chose **Rescrape Item with Custom Query**.  That's the best means to workaround the issue when they can't agree how this condition should be handled.
<img width="1172" alt="custom_query" src="https://user-images.githubusercontent.com/46383815/162264980-946bcb6f-8ada-43a6-9f63-76099c563bd9.PNG">

**Comment by klyco** [comment]
Hey again, that is awesome, thanks so much!  I will do a custom query.

**Comment by 123Venom** [comment]
We had a similar problem with Dexter.  Initially the show was to be called **Dexter Season 9**.  They changed it as a new show **Dexter: New Blood Season 1**.  First few episodes scene releases used the initial naming convention so you had to use a custom query to work around the problem.  They later got their shit together with the uploads.

**Comment by klyco** [comment]
Totally get it, and I remember that one!  

Yes the custom query works a treat, thanks SO much for taking the time to respond to me, I really appreciate it...  Now I'm off to rot my brain with trash TV :-)
