### ISSUE TITLE
LGTM - Code Analysis

### ISSUE THREAD

**Issue by Yaya0312** [123Venom/plugin.video.venom#20]
Your addon is really great, thanks :-)

I recently found this tool and it is great. This may be useful for your project, I hope.
https://lgtm.com/projects/g/123Venom/plugin.video.venom/alerts/?mode=list

**Comment by 123Venom** [comment]
I've used tools like that but they also tend to throw allot of bogus issues that are not real problems like pycharm does but they serve their purpose if you know what really needs attention and fixing.
