### ISSUE TITLE
Search results using german openscraper only offers iload

### ISSUE THREAD

**Issue by Stimmenhotel** [123Venom/plugin.video.venom#21]
Searching for a episode of a series Venom only have search results for one scraper of the german openscraper lib.
It will only find sources on iload for this series/episode. (incl. DDL for another series)...

Since I only use Venom for scraping with the openscraper plugin, I can't check any other addon for similar behaviour, so the fault could be on the openscraper side...

Don't know if it is okay to post a example for a series/episode ... So i won't do that for now.
But it seems to affect movies as well.

Is this a venom problem or should I head over to the os repo?

**Comment by 123Venom** [comment]
your issue is a little confusing to follow but what I'm gathering is your having issues with returned links, in which case you need to head over to openscrapers and post and issue there.

**Comment by Stimmenhotel** [comment]
Okay, thank you.
Wasn't sure where to head first, maybe it is just me picking wrong settings. ;-)

**Comment by 123Venom** [comment]
head on over to os..he may have an answer for you
