### ISSUE TITLE
strings.po duplicates etc

### ISSUE THREAD

**Issue by bjbca** [123Venom/plugin.video.venom#22]
If you are interested, I cleaned up English strings, fixed some order and duplicates, it is here:https://github.com/bjbca/redone/blob/master/strings.po

**Comment by 123Venom** [comment]
I saved it out and will review when I get a chance.  Can you explain a little more in depth so I know what I'm hunting down as far "fixed some order", like give me a case?  When you say "duplicates" did you scan the addon entirely to see the duplicate can be safely removed?  I like an example to check it myself.  While I appreciate your time in this if you really want to help what needs more attention than this is the translation files that I know are way out to lunch at this point and have no had time to deal with that as well...care to have some fun and get your feet wet in what's needed more?  lol

**Comment by bjbca** [comment]
So this all started as i wanted to make some edits for personal use but found things a little confusing so i set about to fix it up for my self.... ran in to a bit of manual labor.... and then i thought i would share
Ok order wise the code has gone something like this:
by line 2029 the reference has run up to #33500 but
at line 2050 it jumps to #35500 and runs to
line 2302 #35563 then jumps back
at line 2306 #33564 and runs
to line 2548 #33892 and then by
line 2558 #35017 and runs to
line 3015 #35573.... so some of the #355xx's get run twice some make blank references, some go blank to being populated later and then for instance
line 2050=#35500=watch
line 2868=#35500=watch
So the file i posted is an attempt get things in order, may not be needed, might just be my personal pref but never the less....
As you know this all takes a bit of time and i dabble when i can... takes me a little longer then others as im just a hacker, not a coder ;)

**Comment by 123Venom** [comment]
ok first of all you do know that if there are gaps in your numbering is does not make or brake a thing as long as your addon does not try to call that number string that's missing right?  The duplicates I can see what I did there, but again it doesn't break anything but it is in fact wrong.  My logic at the time was to copy/paste empty values so in the future I just had to type between the quotes for a new string I was adding so looks like the empty strings I got lost in my numbering.  Honestly of all the complaints you could surely exhaust more time in helping do the translation strings that are far more important and needed than this...That I could use the help on if you're willing?...gladly give you credit for the conv. files to if you could kindly do that and help the project.  I fixed the overlap issue you've brought up and thank you.
