### ISSUE TITLE
EmbyCon & 3rd party Video AddOn Implementation

### ISSUE THREAD

**Issue by Philps** [123Venom/plugin.video.venom#35]
This is a amazon scraper which relies on the external Amazon VOD Addon from Sandman & Varstahl.
It can be implemented in the OpenScraper Section.
Currently it will only check for Prime Content available in germany.

The following changes need to to be made to get it running

- create & copy amazon.py into your OpenScraper Source Folder
- create a Scraper entry in OpenScraper settings.xml and activate the scraper
- SourceCode: https://pastebin.com/wsmMr6nD

You will need to change the addItem function in sources.py as well
Change the following Line 176/177

item.setProperty('IsPlayable', 'true')
#item.setProperty('IsPlayable', 'false')

If this causes issue with others, then a separate query can be implemented to only setProperty for the Amazon Listing

Apology for not submitting a PR but maybe some other contributor is willing to to continue to work this and make it a configurable and mutlilang.

**Comment by Philps** [comment]
This is also possible for many other 3rd parties Video Addons such as Netflix, Maxdome and others
As an example: this was implemented here https://github.com/lastship/plugin.video.lastship/tree/nightly/recources/lib/sources/de

I've also coded an Emby Implementation which is worth looking into as well as a own DB scraper ( feedme ) which can be populate by the user himself

**Comment by 123Venom** [comment]
sorry man really not interested in this.
