### ISSUE TITLE
incomplete movie not showing flag beside the movies name

### ISSUE THREAD

**Issue by Tarek-Depp** [123Venom/plugin.video.venom#38]
Hello, 
I wanted to thank you first for this great addon . 
incomplete movie not showing flag beside the movies name (please open the below link to see the picture so you understand what I mean )
https://imgur.com/TW8gqLV
I don't know If there option for this or it is from the addon it self.
looking forward for your advise. 
thanks

**Comment by 123Venom** [comment]
Not sure I'm following what you're asking about a "flag" here.  Is your arrow pointing to a watched progress/percent indicator?.  What skin is that and what list are you viewing inside Venom?

**Comment by Tarek-Depp** [comment]
Yes exactly watched progress / percent indicator thanks.This Is mq7 liea mode skin.

https://forum.kodi.tv/showthread.php?tid=329255

But it doesn't matter the skin or the list because Elementum addon does. 
When you watch a movie and you stop it before the end you will see you this percentage progress.

**Comment by 123Venom** [comment]
Few things here after investigating this...an addon needs to pass to the skin two properties.
item.setProperty('resumetime', str(xxxx))
item.setProperty('percentplayed', str(xxxx))
neither of which are currently done in any exo fork I'm aware of, Venom included.  I had a look at Seren and it is implemented there.  If Elementum already does this you may want to stick with using that or try Seren.  In the mean time I'm considering adding this in the future so I'll leave this open as my reminder of it.

**Comment by Tarek-Depp** [comment]
Great... Thanks .

**Comment by Tarek-Depp** [comment]
Hi,
Thanks for the new update first.
unfortunately the the watched progress or percent indicator not showing on MQ7 skin.

**Comment by 123Venom** [comment]
Can't answer for that skin but they're showing just fine in Estuary, Silvo, Aura, AuraMod, and AZ2.  Thought that skin was now MQ8?  You might want to ask the skinner if he has a different requirement than just this...
```item.setProperty('resumetime', str(resumetime))```
Here I read a bookmarks.db file for a resume point and pass it to the skin if one exists.

**Comment by Tarek-Depp** [comment]
Unfortunately I got this.
However thanks.
![40044DA2-ACE9-47E0-BCD6-EEDF35FB15FF](https://user-images.githubusercontent.com/37016260/75458467-ea56b300-598e-11ea-857e-495e8606fe35.jpeg)

**Comment by 123Venom** [comment]
well of course you'd get that, sorry I thought you'd know better how to present that question and where NOT to post it.
