### ISSUE TITLE
Thank you. 

### ISSUE THREAD

**Issue by bigpoppapaul** [123Venom/plugin.video.venom#41]
Hey dude, just wanted to say thanks for always keeping everything so up to date and being so on top of repairs when issues arise. It's greatly appreciated.

**Comment by 123Venom** [comment]
Appreciate the kind words!!...we don't hear this often and most devs get frustrated over complaints and quit.  I've been close to that more times than I can count because seldom do people appreciate your free time.  I'm more secluded these days to avoid that bashing.  Granted it's been more than my norm time frame for a Venom update but last few weeks my focus has been on a new OpenScrapers update with fixes and new torrents coming soon.  Then I'm back at it and next update to Venom is going to have uncached torrent removal with setting option to enable/disable.  PM is finished now and testing

**Comment by bigpoppapaul** [comment]
No, thank YOU for keeping everything running so smoothly. Hell, you were even on top of the YouTube api thing in no time. And yes, I know that you likely only hear from people when there is a complaint or an issue, what's worse, you have people bashing you not because you're doing a shit job, but because they don't even have a rudimentary level of understanding of what they're using so they're incapable of doing the most basic troubleshooting when something happens. 
So with all that said, I wanted to send out my appreciation and know that there are tons more out there that feel as I do, but just haven't said anything.

**Comment by 123Venom** [comment]
Really do appreciate that man!!  Had a tweak moments over this guy complaining and pointing figures the addon does this and that in error, yet I helped the dude and my mistake.  Boiled down to api issues and needed workaround code, solved and dude was very ungrateful after I exhausted hours of my free time today...end result is he's is now blocked!

**Comment by ShaVerZ** [comment]
Bang out of order, it only takes a few minutes to respond and update you. Some people are ungrateful, they expect others to help whenever they want it but if others ask for help of them, they help when they choose.

All your work is appreciated at this end mate.

**Comment by bigpoppapaul** [comment]
> Really do appreciate that man!! Had a tweak moments over this guy complaining and pointing figures the addon does this and that in error, yet I helped the dude and my mistake. Boiled down to api issues and needed workaround code, solved and dude was very ungrateful after I exhausted hours of my free time today...end result is he's is now blocked!

Buddy, I feel your pain. I maintain a build for about 40 family and friends with lots of customizations (custom widget menus that I build with text files for new releases, requests, etc., options for touchscreen devices, and much more) and a private facebook group where I keep them updated on everything. I also give them tech support whenever i can. 
Most of them are the most ungrateful bunch of ingrates I could imagine, and these are people I KNOW. So I can't even imagine what you go through trying to help total strangers that feel entitled to your work. So screw that guy, I'm glad you blocked him. 

Keep doing what you're doing for as long as you feel like doing it. You make my life easier by keeping everything so up to date.
