### ISSUE TITLE
Venom displaying episode title instead of show title in TV Shows/Calendar

### ISSUE THREAD

**Issue by RickFromTexas** [123Venom/plugin.video.venom#47]
For example, Gold Rush: Parkers Trail show displayed as Hell's Crack: https://imgur.com/a/KN5rqjj

**Comment by 123Venom** [comment]
yep..recent changes I made to Calendar to speed things up I didn't catch a label assignment elsewhere.  Already fixed and will be included in next update

**Comment by RickFromTexas** [comment]
Great, thank you!
________________________________
