### ISSUE TITLE
[Request] Disable context menu

### ISSUE THREAD

**Issue by brentonv** [123Venom/plugin.video.venom#49]
Hi @123Venom thanks for the great add-on. I'm just wondering if you might please consider including an option to disable the context menu.

I use jurialmunkey's Arctic Zephyr 2 skin and TMDBhelper widgets and rarely interact with the Venom add-on directly and don't require additional context menu items. 

Thanks mate!

**Comment by 123Venom** [comment]
are you referring to the global context menu options?  I assume so since you mentioned widgets.  You can uninstall that addon and the items will be removed.

**Comment by brentonv** [comment]
Ok thanks. I thought it automatically installed from Venom and from updates. I'll take another look.

**Comment by 123Venom** [comment]
ya I think I spoke to soon and believe it's a dependency so it won't allow it to be uninstalled.  I'll ponder this with a few ideas.

**Comment by brentonv** [comment]
If it's complicated please don't worry about it. If the context menu items only show up when using Venom then it's not an issue.

**Comment by 123Venom** [comment]
new version of `context.venom` now has new ability to turn off context menu items via new settings menu.  If you uncheck all it basically now does nothing, which seems to be what you wanted.  Closing this now that it's been addressed.

**Comment by brentonv** [comment]
Very awesome. Thankyou
