### ISSUE TITLE
Wicked slow

### ISSUE THREAD

**Issue by ricklepick** [123Venom/plugin.video.venom#5]
I love that this is being maintained and the new features, but compared to Exodus redux the speed of Venom is about half. It's loading from Trakt very slowly (My TV/Progress) and both scraping and url resolution are very very slow. Sometimes it's literally 5 minutes from start to play. I'm on Rpi3 running osmc + Kodi 17.6 and have done a bare metal install today to see what might be the cause. Venom and ER are all I have installed and I'm using Real-Debrid and my own API keys for Trakt, over a 200 mb cable conn. No VPN. ER is swift. Venom crawls. I also removed the Iwaatch and other supposedly defunct resources from RESOLVEURL per stuff I read on Reddit. Please let me know what I can provide to help debug this. 

My typical use-case is this:
- Open Venom
- My TV \ Progress. This refreshes from Trakt and is sometimes slower than ER.
- Click an episode. This either displays a new list of all un-watched episodes in the season (after a wait) or starts search for the episode. The search is where the slowdown really shows. I've seen this take 2-5 mins itself.
- List of sources finally opens. Click one. Here I get "Waiting..." for up to 5 mins sometimes. Certainly slower than ER.

RESOLVEURL and Real-Debrid settings are default. I know I can reduce time by setting Debrid-only, reducing providers etc. but even when I turn everything off and just use 'paid' sources the flow above is slow compared to ER. It's like some code has been added that is slowing this all down.

**Comment by tmjvonboss** [comment]
I did notice venom is slower than ER too when I initially switched, not sure why either

**Comment by ricklepick** [comment]
https://www.reddit.com/r/Addons4Kodi/comments/c8kneb/openscrapers_update_v00190_fixing_scraping_issues/?utm_medium=android_app&utm_source=share

I think this was it. Last night V was blazin' after I applied those OS updates.

**Comment by drinfernoo** [comment]
Unfortunately, OpenScrapers seems to work much faster *without* `js2py`, but it's the only really feasible solution we have to the CloudFlare challenge :(

**Comment by tmjvonboss** [comment]
so maybe we should work towards a js2py in c++ and make some.l python bindings rather than relying on a pure python implementation to try to speed things up? or should we try to filter out malicious js code?

I'm saying "we" but not really referring to a group of people here, just eh, i guess talking we as.in the community
