### ISSUE TITLE
Issue with Remove HEVC streams

### ISSUE THREAD

**Issue by Spooge-DAmour** [123Venom/plugin.video.venom#52]
I noticed with change in 3.6.5 when the Remove HEVC streams option is selected after the scrape I am getting the 'No Venom Streams Found' error, despite plenty of non-HEVC/x265 streams being found.  Confirmed this by doing the same scrape with the option turned off.

I try to avoid the HEVC streams as I don't like the tearing and screen artifacts it creates on my larger displays.

Thanks and keep up the great work.  It is greatly appreciated.

**Comment by 123Venom** [comment]
yes there was an issue with "Remove HVAC" and also "Remove 3D".  These two options looked inside the scraper supplied dict `sources` for a key `info`.  Unfortunately I never noticed that half the free hosters have this key missing so it breaks using `info['HVAC']`.  I fixed both conditions in the addon by using `info.get('HVAC')`, which does not throw a key error when it does not exist.  The other thing I did was fix all OpenScrapers that are missing this `info` key.  I'm working on OpenScrapers update now and will have an update pushed for both hopefully today.

**Comment by 123Venom** [comment]
The reason I didn't initially detect this issue was because I did not enable enough free hosters during testing where the problem lies...bout half, or little less, had that missing key.  Always something but I try to fix it once spotted.

**Comment by Spooge-DAmour** [comment]
Thank you sir.  Keep up the great work.

**Comment by 123Venom** [comment]
Let me know if v3.6.6 cured the two issues for you and I'll close both.

**Comment by 123Venom** [comment]
@Spooge-DAmour you all set with this one?

**Comment by Spooge-DAmour** [comment]
Looks good sir!  Thank you.
