### ISSUE TITLE
Sources not playing from library since latest update(s)

### ISSUE THREAD

**Issue by githubman888** [123Venom/plugin.video.venom#55]
Hello thanks first for your work
I would like to report a problem which some people reported on reddit also
Since the updates past version 3.6.4, items that are in kodi library wont play anymore
They scrape as normal but if a link is clicked to play it,then nothing happens
The same items still play fine from within the venom addon,but play functionality from the library has broken (this is with tv shows im not sure about movies as i didnt try this as i only have tv shows in my library)
Thanks

**Comment by 123Venom** [comment]
I'll dig into this....sounds like a change I made to the either player module or the path to play may have broken this.  I'll report back...sorry busy work day

**Comment by githubman888** [comment]
No problem and thanks

**Comment by 123Venom** [comment]
I pushed an update for this..let me know if all set and i'll close this.

**Comment by githubman888** [comment]
I just got the update and it is working again now
Thanks for this

**Comment by 123Venom** [comment]
good deal
