### ISSUE TITLE
Venom is pulling/displaying some foreign clearart

### ISSUE THREAD

**Issue by Retrogamer3791** [123Venom/plugin.video.venom#56]
Venom has been pulling/displaying Foreign Language Clearlogos with some items. (Spanish/Frensh,Russian etc).

 is especially noticeable with Studio Gihbli Films.

https://imgur.com/a/JNgiVEj

I have cleared All cash & deleted all cashed thumbnails

**Comment by 123Venom** [comment]
Found and fixed..happened under some rare conditions being met and was a bugger to find, one being foreign artwork with more likes than eng where only 2 lang titles existed.

btw..that's not clearart.  That's landscape to kodi and pulled from fanart.tv's `TVThumbs`
https://fanart.tv/series/318408/planet-earth-ii/

Fix will be included in next update pushed.
