### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by nepalicana** [123Venom/plugin.video.venom#57]
Can you add some more scrappers such as uwatchfree, vmovee, hdmo? Most of the scrappers u have is also included in other addons like venom but these scrappers aren’t available in non in the other addons? Would be grateful if you could add these.....

**Comment by 123Venom** [comment]
>>Most of the scrappers u have is also included in other addons like venom<<

Sorry but that does not makes sense...this is Venom's github and those three site you listed are not in OpenScrapers so Venom does not use them.  Javascript loaded sites are beyond my abilities to scrape.

**Comment by nepalicana** [comment]
Thanks mate for your explanation
