### ISSUE TITLE
sources.py - "filter_dupes(self)"

### ISSUE THREAD

**Issue by kasi45** [123Venom/plugin.video.venom#61]
Please change in the file "sources.py" the function 
"filter_dupes()" If the value of "i[ur]l" is not a string, the operation is aborted. 
Example: u'url'": [0, u'3143', 1]"

new:

- insert  try & except
- change var a and b - to str()

[filter_dupes.txt](https://github.com/123Venom/plugin.video.venom/files/4716324/filter_dupes.txt)

Please excuse my poor english.

**Comment by 123Venom** [comment]
I'd actually like to see a log where any url passed from the scrapers is anything but a string?  it's never an int() like your example.

**Comment by kasi45** [comment]
The value of the variable "url" can be a list. 
This list "url" is then used later in the function 'resolve()' to resolve a link. 

The function "filter_dupes()" assumes that the value of "url" is a string. 
so i['url'].lower() is then successful.
but not if i['url'] is a list

Code line from scraper:
`sources.append({'source': hoster, 'quality': quali, 'language': 'de', 'url': (e, h, url, isCaptcha), 'info': "Recaptcha" if isCaptcha else '', 'direct': False, 'debridonly': False, 'captcha': isCaptcha if isCaptcha else False})`

**Comment by 123Venom** [comment]
what German scraper in OpenScrapers is passing the url as a list?  I did a scan for some of those key/values and did not turn up a match in our scraper package.  My hunch also says if the url is returned as a list is going to break in other places than the filter_dupes() function.  The intent is the url passed is a link to the media to be resolved by resolveURL.

A full search for `'url': (e, h, url, isCaptcha)` didn't exist.

**Comment by 123Venom** [comment]
and I'm sorry but your try & except block is completely wrong.  You put it outside the sublist loop and with `fiter.append(i)` being inside it never adds the first `i` to sublist and you end up with a source list of 1 link...lol.  Did you test that?  Here's the fix and logging even added to capture exception

[filter_dupes-1 - Copy.txt](https://github.com/123Venom/plugin.video.venom/files/4721447/filter_dupes-1.-.Copy.txt)

**Comment by kasi45** [comment]
I ported a scraper from lastship to a private version of openscrapers.

You can compare with hdstreams in this repo https://github.com/lastship/Lastship-Repo/blob/master/plugin.video.lastship/plugin.video.lastship-4.0.6.3.zip

**Comment by kasi45** [comment]
>  I'm sorry but your try & except block is completely wrong

 try & except block is OK

```
for i in self.sources:
    try:
        a = str(i['url']).lower()   # here is the first critical event
        for sublist in filter:
             ...
    except:
        log_utils.error()
        pass
```
and of course I have tested everything before the posting


`

**Comment by 123Venom** [comment]
ya so did I and 5 titles left me 1 link till I looked why.  Sorry but I'm declining this.  Sounds like your custom work is better suited to fork Venom and do what you'd like to it.

**Comment by kasi45** [comment]
Then don't. 
I do not use their addon, I have my own.
There is also the Base Exodus.

But I planned to publish german, up-to-date and working scrapers at "openscrapers". During a cosstest I noticed that your addon found results, but then didn't show the found results.
Thereupon I searched in your addon and found the reason for that. 

Now I regret that I wasted my time for debugging your addon instead of continuing to work on my project.

**Comment by kasi45** [comment]
> Sounds like your custom work is better suited to fork Venom 

And what I forgot to mention - there are still enough lines of code in 'Venom' that I once wrote, or other contributors

**Comment by 123Venom** [comment]
>>Now I regret that I wasted my time for debugging your addon instead of continuing to work on my project<<
Look man since since you feel the need to get the last word and be a little twirp about it after it's closed I'll bite and reply to your little game.
1.) you make a suggestion to fix a scrape issue and later find out this scraper you're toying with is not apart of OpenScrapers we support...ya ok.
2.) You suggest a try & except block with a for loop inside it.  The value of sublist upon first pass is what exactly?  try `[]` so it's intended to blow up first pass so the first url is appended to the list but inside the try & except block it's broken and the append doesn't happen and you're left with 1 link after the function runs...and I want that?

All for legit PR's but this was bad.

**Comment by kasi45** [comment]
> All for legit PR's but this was bad.

maybe I misspelled PR and inserted the lines wrong
I'm gonna check this one more time.

**Comment by 123Venom** [comment]
> 
> 
> I think today was a "bad" day!
> If we were both a little more open-minded, I think we could learn somethink from each other.
> 
> Peace?

Agreed!  I'm usually humble and maybe just in a mod today
