### ISSUE TITLE
Re-scrape item option disappeared from options on library items

### ISSUE THREAD

**Issue by Toweliechaos** [123Venom/plugin.video.venom#65]
This vanished a while back and got restored and has vanished again.

TV show in library. Scan for sources. Cancel. Go to scan sources again and just provides the previous list, even if you cancelled straight away and only got 1 source, you'll just get that 1 source forever. 

Hope this makes sense. Have video available if not.

**Comment by 123Venom** [comment]
looks like once again I forgot about those damn strm library files.  This will be fixed in next release.

**Comment by Toweliechaos** [comment]
Ha, thanks. I inadvertently contacted a different venom developer on github who was struggling to understand the problem!   
  

  

  
  
 Sent from Edison Mail for Android  

  
  
  
  
  
>

**Comment by 123Venom** [comment]
I'd venture a guess without combing his github issues it was Venomous the dev of cloudscraper

**Comment by 123Venom** [comment]
Have not forgotten about you.  Major update coming next week or two that adds season/show pack scraping.  Your fix is part of the coming update.

**Comment by Toweliechaos** [comment]
Hi
  

 Thank you for your help.  

  

  

  
  
 Sent from Edison Mail for Android  

  
  
  
  
  
>

**Comment by 123Venom** [comment]
Just pushed 4.0 out and the fix is included in that so closing..enjoy!

**Comment by Toweliechaos** [comment]
Thanks so much.  

  

  

  
  
 Sent from Edison Mail for Android  

  
  
  
  
  
>
