### ISSUE TITLE
Up Next without autoplay

### ISSUE THREAD

**Issue by bigpoppapaul** [123Venom/plugin.video.venom#66]
Hey man, 

Just a quick question and I'm sorry if I've missed it in the settings. Is there a way to get the upnext functionality to scrape while watching the episode but to present a link directory at the end of the episode instead of autoplaying?  If not, not a big deal, just curious. 

Thank you for an amazing addon that is maintained better than any other out there.

**Comment by 123Venom** [comment]
Sadly no.  It's in my notes to do a background scrape process for the UpNext usage but I've just not gotten to it and frankly it's near last on the priority list.  The dev of UpNext mucked things up for 3rd party addons so it doesn't work beyond v1.0.1 and AddonSignals v0.3.  Those two requirements is why priority is low on it.  Even once I get around to that I'm not changing the UpNext functionality from what the addon itself was designed to do...continual playback.  Even Kodi's built in `Play from Here` will not work properly if an addon is not in the `AutoPlay` mode.  Sorry and wish I had better news for ya but that's the bottom line right there.

**Comment by bigpoppapaul** [comment]
All good man, wasn't trying to add to your plate, was just wondering. Thanks for getting back to me so quickly.

**Comment by 123Venom** [comment]
Appreciate that.  I really am sorry I didn't have better news for ya. I just thought it best to not sugar coat the situation and just be straight with it.

**Comment by bigpoppapaul** [comment]
Oh man. Don't even worry about it. It's literally an extra button press or two. I think I can handle it. :)

You do a LOT of work on this thing. I was just making sure I didn't accidentally overlook the feature. :)
