### ISSUE TITLE
Kodi crashes on startup after installation

### ISSUE THREAD

**Issue by sandorex** [123Venom/plugin.video.venom#67]
I installed the venom using the repo and it crashed, afterwards it crashes every time i launch it

[kodi_crashlog-20200715_172528.log](https://github.com/123Venom/plugin.video.venom/files/4926210/kodi_crashlog-20200715_172528.log)

```console
$ kodi --version
18.7 Git:20200703-nogitfound Media Center Kodi
Copyright (C) 2005-2020 Team Kodi - http://kodi.tv
```

I am using `Fedora Workstation 32`

**Comment by 123Venom** [comment]
Sorry but not going to be of any help with Fedora Workstation.  Some of the errors in that log look to be having issues with even standard kodi library modules.

**Comment by sandorex** [comment]
You're probably right, it has been crashing sometimes, ill try flatpak
