### ISSUE TITLE
{Enhancement] More Anime Catagories

### ISSUE THREAD

**Issue by Goldenfreddy0703** [123Venom/plugin.video.venom#68]
Hey, i love your addon and i love that you added a an anime section and it would be so cool to add more anime categories from Kitsu. Would there be a possibly chance to add more anime scrappers or more anime categories for your add-on. Your probably the only person who has an anime section for a type of addon that gets you good streams and good stuff. I like your addon and i would this addon to be the 1st addon for an anime section for real debrid or premiumlize me.

**Comment by 123Venom** [comment]
I got into a little awhile back and anime is a whole different animal, and very difficult to deal with due to titling discrepancies.  I walked away from it then because it's more work than I'm willing to spend on it.  Sorry!

**Comment by Goldenfreddy0703** [comment]
It's ok I understand and thank you for responding. It's just so hard to find an anime addon these days that can actually stream anime. So far wonderfulsubs or Watchnixtoons is the only ones but the metadata is not good at all with these addons and the hummingbird anime dev is always busy.
