### ISSUE TITLE
[REQUEST] File Size Limit for Pack Scraping

### ISSUE THREAD

**Issue by Zero3ffect** [123Venom/plugin.video.venom#69]
I love the new pack scraping feature.  Thanks for all work you've put into always improving Venom.  Would it be possible to add a file size limit slider for packs?

**Comment by 123Venom** [comment]
I actually had one more item on my to-do list and that was to change how the file size for pack files is reported.  Right now you're getting the size of the pack and I want it to be the approx size of each episode in the pack.  I just was super burnt out coding yesterday and needed a week break so frankly I said fuck it and pushed it without my last item dealt with.  I'll add your request to it for when I get back at...right now I need the week off from coding a thing.  That whole pack support took me nearly a month and many hours.  That's also with two guys as Tikipeter (FEN dev) was part of that project.

**Comment by 123Venom** [comment]
I uploaded a v4.0.2a to dev branch you can test for the new pack file size change so it's based on a single ep.  That should now allow it to work with the max file size slider.
[https://github.com/123Venom/zips/tree/dev](url)
