### ISSUE TITLE
Subtitle 

### ISSUE THREAD

**Issue by tomtomclub** [123Venom/plugin.video.venom#70]
Subtittels doesn't work anymore 
In the addon

**Comment by tomtomclub** [comment]
Yes I it works on open subs test it 8 movies.  But the subs in de addon settings is not working  if you want I can make a log four you 
Its Dutch subtitles

**Comment by tomtomclub** [comment]
Yes working with AK4 thanks

**Comment by 123Venom** [comment]
yes being on keybase as I am I had worked with the dev to find out he has a strict requirement to pass the IMDb_id to a property for `A4KSubtitles` to work well.  I made sure to include that so should be nice and smooth for ya. ``A4KSubtitles` uses more services to `OpenSubtitles, BSPlayer, Podnadpisi.NET, SubDB, Subscene and Addic7ed.`  There's 5 additional ones he uses so your success rate will be far greater!!  Enjoy!
