### ISSUE TITLE
Quick question (not an issue)

### ISSUE THREAD

**Issue by bigpoppapaul** [123Venom/plugin.video.venom#72]
Hey Venom, I'm hoping maybe you can give me a quick bit of help here. I'm playing with some older addons as I'm learning about the manipulation of python to get what I want. This is not for my own entertainment kodi set-up but one I play with as I learn things.  
So my question is, in openmeta, it's possible to incorporate a json file to get things to play with venom very simply, I'm just wondering, would it also be simple to also set up a json file to incorporate your trakt manager as an option in the openmeta play menu? 
I know openmeta is discontinued and all that, I'm just using it to learn and this is something I'm curious about.

**Comment by bigpoppapaul** [comment]
Disregard. You gave exactly the info I needed to drinfernoo and he set it up, so thank you. :)

**Comment by drinfernoo** [comment]
To be fair, all credit on this one should go to @123Venom 👌

**Comment by bigpoppapaul** [comment]
All I know is, no credit goes to me. So thank you @drinfernoo and @123Venom for this. I really appreciate it.

**Comment by 123Venom** [comment]
@bigpoppapaul did you also get the 2 player files I updated for OpenMeta?  Sorry I didn't answer you sooner I just had not had a chance to look at it but dr. got me on keybase...lol.

**Comment by bigpoppapaul** [comment]
@123Venom All good man, yeah, thank you, I got it from the good doctor after you passed it on to him. :)
