### ISSUE TITLE
Show Information before Playing link

### ISSUE THREAD

**Issue by kodiuser-xiii** [123Venom/plugin.video.venom#77]
Hi,
I was not sure where to raise this question/feedback. I also had no luck finding this info on the net. This feature may be existing but I could not find it under the addon settings menu. If not, then could you consider adding this as new feature? 

I am using Kodi 18.8 on a Windows 10 PC with Auro MOD skin. 

Is there a way in Venom where when you click on a show/movie it displays the information of the show/movie before it finds/plays the link. 

This would really align with the Kodi player feature where it allows files in your library to first display the information before playing the file.

Please advise.

**Comment by bjbca** [comment]
If you right click or long press on the link a context menu should pop up then scroll down through the menu and select "Information"

**Comment by 123Venom** [comment]
I know what he wants to do...pretty sure FEN has this now where you can custom set the default action when you select an item to show `info` or `play` action.  I'll look into it but I got a long list of items now so prob won't get to this any time soon.

**Comment by kodiuser-xiii** [comment]
@123Venom  That is alright, thanks for taking a look at this feature and adding it to the list of enhancements.
