### ISSUE TITLE
& escape in setting.xml

### ISSUE THREAD

**Issue by rrosajp** [123Venom/plugin.video.venom#8]
hi @123Venom
btw it's not issue. but u may like to change this in setting file
& escape in 'RunPlugin(plugin://......'  all urls in setting file

here i did on your setting file,file is same just added & escape
https://gist.github.com/rrosajp/232b480e4553f1b2ca29aca9bd6c5735

**Comment by 123Venom** [comment]
please use PR for suggested changes.

I visited this topic about 6 months back so I'm going to rough out this response.  I was told the escape is not needed in this condition.  I checked other addons to see and most all do not escape the & these days.  I tested escaped and not and noted no difference so I stopped using it.

**Comment by 123Venom** [comment]
this was needed for the new userdata settings.xml clean tool...seems kodi doesn't care if the escape characters are there but ElementTree chokes without them when trying to parse it.  Closing this one.
