### ISSUE TITLE
The my accounts addon is not saving the data

### ISSUE THREAD

**Issue by chrisnikol** [123Venom/plugin.video.venom#81]
When i saw the description about the my account addon i was very happy. Actually i was thinking the same thing why the user to enter at every addon the same acoounts every time. It would be very good if all the addons can read the settings automatically from a kodi file.

The problem i am facing is that although i authorize my accounts and trakt, debrid etc and looks like the authorization was successfully i press ok, but if i enter to the my accounts addon again all the settings are gone, like the addon at the end dident actually save the settings.

Of course this issue dosent mean that i am not gratefull to you and for the venom addon and for this briliant idea to make my accounts addon.

**Comment by 123Venom** [comment]
Interesting.  Not having that happen on 3 devices here.  Did you try to restart kodi?  As a test do a simple one say `IMDb` where no auth is needed and hit OK after adding...is it saved?  If you enter `My Accounts` from Venom's settings it will also auto sync the changes back to Venom.  If you've done changes to `My Accounts` outside of Venom then in Venom's settings under accounts is a `Sync(Re) My Accounts` that should bring the changes in....but of course that's providing the `My Accounts` settings are being saved.  If `My Accounts` is not saving changes it sounds like something is wrong with the `user_data` settings.xml.  I'd check if that file is being updated, which kodi handles.  What device?

**Comment by chrisnikol** [comment]
After your message i tried the same procedure to another device that i also have installed the kodi there. At the second device the settings was saved without any problem.

Then i went to the device with the problem (win 10 64bit with kodi 18.8 64bit) and noticed that for some reason the kodi dident create the folder script.module.myaccounts inside the addon_data folder as it should.

Trying to understand why, i noticed that for some reason the kodi folder (where the kodi keeps all the settings) had the read only  attribute. After i remove the read only attribute from the kodi folder and subfolders i repeat the procedure and success. This time the settings was saved without any problem.

Thank you for your help and sorry i wasted your time for nothing. I should invistaged the issue further before open an issue here.

**Comment by 123Venom** [comment]
Glad you got it sorted out
