### ISSUE TITLE
Movie and Episode maximum filesize lower to 2gb

### ISSUE THREAD

**Issue by jaimsitecom** [123Venom/plugin.video.venom#90]
The latest update made changes to separate filesize filter for movies and tvshows. But hopefully we can have option lower than 5gb. I don’t need my tv shows having 5gb size. Am already satisfied with 1gb or even lower actually. Even movies I don’t need hdr or dolby’s, so max of 2gb movies are enough for me. Loads faster and already satisfactorily clear enough for my 50inch tv even at 720p movies. 

Again, hoping you could lower the maximum filesize for both movies and episodes in the ‘SOURCES FILTERING OPTIONS’ down to 2gb. 

Ty

**Comment by 123Venom** [comment]
```
range="5.0,0.3,200"
```
You can change the 5.0 to 2.0 for now in settings.xml if you want for both cases that appear in the file.  I'll consider this.

**Comment by jaimsitecom** [comment]
Ty! i will do that.
