### ISSUE TITLE
Trakt authorization. 

### ISSUE THREAD

**Issue by Blackysbd** [123Venom/plugin.video.venom#91]
Keep getting annoying reauthorize trakt issue with venom (no disrespect to the dev). Tried reauthorize in my accounts as well as clearing all cache, even deleting and reinstalling all addons on a fresh install.

I opened up the settings xml in both my accounts and venom and noticed the Trakt token and Trakt refresh were different. Cut and pasted from my accounts to venom and since then I have had no further pop ups.

Would be interesting to know if anyone else who gets the issue could check their xml's.

**Comment by 123Venom** [comment]
Unfortunately a few of us tested and were not able to duplicate the issue but we are aware some have had this problem.  We've identified a circumstance where such a case could happen and altered the code in hopes it's avoided.  The latest version should hopefully address the issue and you may need to re-auth Trakt in My Accounts.  Let me know when you get a chance to test the latest **My Accounts v1.1.1** and **Venom v5.1.9**

**Comment by Blackysbd** [comment]
Thanks for the reply, I have updated both My accounts and Venom and the
issue seems to be resolved.
Appreciate all the work.

Many thanks

**Comment by 123Venom** [comment]
That's good to know and thanks for keeping me posted.
