### ISSUE TITLE
Info request: Params for opening search window

### ISSUE THREAD

**Issue by Alfiegerner** [123Venom/plugin.video.venom#92]
Hi,

I'm wondering if someone could help me with parameters required to perform a search from an external app.

E.g. I added this [PR](https://github.com/OmerTu/GoogleHomeKodi/pull/337#issuecomment-838736044)  to GoogleHomeKodi to use voice to search for movies and shows in Kodi via Seren

I'd like to do the same for venom, but am struggling to work out what windows Params I need.

For Seren I pass this as a window param for shows:
```
"plugin://plugin.video.seren?action=moviesSearch&actionArgs="+searchString;"
```
Does anyone know the equivalent for Venom?

Thanks!

**Comment by 123Venom** [comment]
Sorry but due to a recent change to Venom's search method the action is now a ```Container.Update()``` which more than likely will not work with Google Home.  I'd suggest you stick with Seren.

**Comment by Alfiegerner** [comment]
Hi @123Venom  - if I can call a built in I can (maybe make it work).

It looks like Container.update should be callable externally: https://kodi.wiki/view/List_of_built-in_functions#GUI_container_built-in.27s

Can I pass a no search string in or no go?
