### ISSUE TITLE
latest venom version not working

### ISSUE THREAD

**Issue by jjplano** [123Venom/plugin.video.venom#93]
hi! I was using Venom since last year without any issues on Kodi/raspi. but I kept getting the message that there was a newer version on the repository, so I did the update.

now I can't see anything on it. when I do a scrape it founds multiple options for new shows, but when resolving not a single one of them plays, and sometimes I get the message of buy a premium account or activate the free mode. sometimes it founds an available source and then when it's gonna play it stops without error. I have set a trakt account, a premiumize one, a filepursuit one, a furk.net one

am I missing something? this used to work so good :(

**Comment by 123Venom** [comment]
what Kodi version?  Did you verify that all account settings that you setup in the My Accounts addon were synchronized back to Venom and are seen in the Venom settings to be correct?  Sorry not having that problem nor ever experienced it.  I'd try clearing all cache and restart device.

**Comment by jjplano** [comment]
thanks for replying. Kodi version 18.9.0 on LibreELEC 9.2.7. I verified that the settings on My Addons were synchronized on venom and they seem correct there. I removed all cache and restarted, no luck, I still can't see anything =(

is there a step by step on how to configure Venom in case I'm missing something? the weird part is that it was working ok up to the last update

**Comment by 123Venom** [comment]
There's no how to writtten..sorry.  Wish I could help you more bud but never seen this issue nor have that matching hardware to test.  I'll also be dropping Kodi 18 support for even discussions as I no longer use it nor wish to continue firing up two version for testing and the time it eats up doing so.
