### ISSUE TITLE
Resume doesn't seem to work when playing through tmdbh+strms

### ISSUE THREAD

**Issue by Logs22** [123Venom/plugin.video.venom#94]
Hello! Ive been faced with this issue that is a little strange. When exiting from a video somewhere in the middle, i get a notification saying that playback prgress has been saved at x time. going back into the scrapers and trying to resume from this time seems to be the issue. [here is a video of the issue](https://i.imgur.com/i58RFxu.mp4) sorry that it is a little long, I wanted to make sure that no errors were thrown after the fact. [Here is a log](http://paste.kodi.tv/uvuhepigiq).

Other information - Kodi 19.1, nvidia shield, android, and using tmdbhelper and strms, with the venom source select player, and the trakt addon for scrobbling. The option for scrobbling is disabled in the venom settings just like it reccomends.

**Comment by 123Venom** [comment]
When I coded the Trakt scrobble in Venom I never took in account the Trakt addon for integration.  Currently Venom sends the scrobble to Trakt and writes a matching database entry.  This data sync between Trakt and the Venom db is checked every 10mins as a service so your other devices will be in sync as well.  If you disable the scrobble in Venom the sync does not take place and you'll be on the old local bookmark handling method.  What you ask of is possible with work but I'm afraid with my current to-do-list and life duties I won't be getting to something like this any time soon.  I'd suggest you trying to use the Venom Trakt scrobble.  I'm not even fully convinced letting both handle that scrobble will really hurt anything other than the last one to send the scrobble will govern the offset used.

**Comment by 123Venom** [comment]
I just looked up some info on Trakt scrobble case if sent in short duration of time for same item.  Quoted from a post
>>Trakt does send a 409 response code if the same item is scrobbled too many times in quick succession. This timeframe appears to be one hour, according to the example response from Trakt's API documentation:
I still tend to doubt it'd hurt much, prob the 409 is just a response and is ignored.

**Comment by Logs22** [comment]
Thanks for the response. I 100% understand. I'll play around with it and see if I can get anything to work, if not it's no big deal!
