### ISSUE TITLE
Clearlogo not working

### ISSUE THREAD

**Issue by djdirty60** [123Venom/plugin.video.venom#99]
Good day,

Why does the Clearlogo not work through the trakt lists and watchlist!  And it's not visible in the player either!  Is that correct?

 thanks in advance

![1625516502990149187746372373539](https://user-images.githubusercontent.com/13561831/124515316-71b40200-dddf-11eb-98c1-31075c2df984.jpg)

![16255179327527103942215700866230](https://user-images.githubusercontent.com/13561831/124516766-bd1bdf80-dde2-11eb-8bde-81d45be26571.jpg)

**Comment by 123Venom** [comment]
clearlogo displays perfectly fine.
<img width="908" alt="clear_log1" src="https://user-images.githubusercontent.com/46383815/124519218-a65f9380-ddb6-11eb-81a3-f721c5798908.PNG">

Had a fellow user test for me as his results
![clear_log2](https://user-images.githubusercontent.com/46383815/124519238-b5464600-ddb6-11eb-91bc-cb8fb31c1628.png)

You don't have the **Disable Extended artwork(fanart.tv)** on by mistake right? 
Try clearing cache and metacache.  If still not showing try switching the view in you skin see if there's a skin issue by chance but his AurMod shows the clearlogo's just fine in his view.

**Comment by djdirty60** [comment]
Het werkt, moest blijkbaar kodi herstarten... thnx

**Comment by djdirty60** [comment]
One more question, is it true that you don't see the Clearlogo of a series from library in the player, because it does for a movie?

Serie
![16255222009235861434050543244907](https://user-images.githubusercontent.com/13561831/124520401-aed2c100-ddec-11eb-9fae-4ff6555d4cba.jpg)
Movie
![16255222832066561958245597507725](https://user-images.githubusercontent.com/13561831/124520462-df1a5f80-ddec-11eb-9c7c-d7064681e05e.jpg)

**Comment by 123Venom** [comment]
Artwork for library items is fetched via the scraper you use....not an addon that put the library .strm item there.  I do not believe TVDb scraper scrapes artwork from fanart.tv last I checked, could be wrong I'd have to peak at it again.  I use TMDb scraper and it handles fanart.tv fine for both movies and tvshows so I get clearlogo artwork WHEN it's available.

**Comment by djdirty60** [comment]
That's right, I also see the Clearlogo in my library, just not in the player, and I use the tmdb tv Show information addon, there I can fill in my fanart api.  And for movies the movie database python, in both the fanart api's are filled in

Tmdb tv Show Information addon
![16255238913369006635639176140947](https://user-images.githubusercontent.com/13561831/124521649-9cf31d00-ddf0-11eb-8762-c61c9fbb10f6.jpg)
the movie database python
![16255242196706380437142742752445](https://user-images.githubusercontent.com/13561831/124521870-5eaa2d80-ddf1-11eb-9510-03d3fdc7ec07.jpg)
Serie in library
![16255239449863501165581167333851](https://user-images.githubusercontent.com/13561831/124521680-be540900-ddf0-11eb-825f-c6e6ec5dfc13.jpg)
Player
![16255240155342047882323068564358](https://user-images.githubusercontent.com/13561831/124521729-e5aad600-ddf0-11eb-86a6-189713d3631f.jpg)
Movie in library 
![16255241255203879198512849906430](https://user-images.githubusercontent.com/13561831/124521801-27d41780-ddf1-11eb-93d1-8fdad14536cf.jpg)
Movie player
![16255241003359109961768096686843](https://user-images.githubusercontent.com/13561831/124521787-1854ce80-ddf1-11eb-87e5-966c0c768e7c.jpg)

**Comment by 123Venom** [comment]
When you are highlighted on a series in the library pull up the context menu **Information**. Select the tab for **Choose Artwork**, or **Artwork**, whatever it may be called.  You see be able to see the list of artwork available that your TMDb scraper returned.  Is clearlogo shown?

<img width="985" alt="library_clearlogo" src="https://user-images.githubusercontent.com/46383815/124522413-2d196e00-ddc1-11eb-9f1a-0910763e0709.PNG">

Player clearart is showing perfectly fine for a library episode item
<img width="1062" alt="player_clearart" src="https://user-images.githubusercontent.com/46383815/124522574-c21c6700-ddc1-11eb-897d-5e5cc183aaf2.PNG">

**Comment by djdirty60** [comment]
Yes it showing

![16255256944692581025292697409774](https://user-images.githubusercontent.com/13561831/124522823-d6c62280-ddf4-11eb-9b47-df4b8916c9e2.jpg)

![16255257395251442206756283631931](https://user-images.githubusercontent.com/13561831/124522860-ee051000-ddf4-11eb-8b44-00b9172c1276.jpg)

**Comment by 123Venom** [comment]
then if the artwork is indeed available it would mean something is amuck in my player module for your case.  Interesting I can't duplicate it.  Your system is obliviously set for Dutch but it did not look like the Venom setting for api language was set to Dutch as well..that right?

I'll test that title and see what I can find and report back when I get a chance

**Comment by djdirty60** [comment]
Systeem language is Dutch and Venom api language is Dutch

**Comment by 123Venom** [comment]
idk bud I can not duplicate the issue.  I switched both the system lang and Venom's api lang to Dutch and the player still pulls the available clearart in the player for me.
<img width="1072" alt="clearart2" src="https://user-images.githubusercontent.com/46383815/124532330-51377800-ddde-11eb-986e-2d333d45030b.PNG">
Are you using TMDB Helper by chance?  I'm still poking around.

**Comment by 123Venom** [comment]
I even just tried your exact show.  Added it to my library and played it..clearart still seen
<img width="1064" alt="7worlds_1" src="https://user-images.githubusercontent.com/46383815/124533832-0f5c0100-dde1-11eb-9b4d-b294aa679481.PNG">

Then flipped system lang to Dutch
<img width="1064" alt="7worlds_2" src="https://user-images.githubusercontent.com/46383815/124533865-1daa1d00-dde1-11eb-849b-118e8a5b52b3.PNG">

When you bring up the Source Select as the top of the skin do you see the clearlogo like so....?
<img width="1048" alt="7worlds_3" src="https://user-images.githubusercontent.com/46383815/124533924-3ca8af00-dde1-11eb-9042-e3aa9abace05.PNG">

**Comment by 123Venom** [comment]
I believe I just duplicated it.  Are you set to AutoPlay?  The problem is I did a complete re-write to pull extra meta, mostly artwork, from the Kodi library to satisfy that new window xml skin that you see in the Source Select pic I posted above.  That meta pull is then passed to the player so that clearart and clearlogo shows fine for me when set to Source Select.  I never did a re-write of the meta under an AutoPlay condition because I did not need the artwork to display like in the pic, an afterthought.  When I just now switched to AutoPlay, and cleared Venom cache, I then now had no clearart in the player.  I believe I can fix that by re-writting the meta in the player to pull the **art** from the Kodi library to match what I did when sources are fetched.
If I'm right about this and you are using AutoPlay you should be able to test this for me and switch it to Source Select and see if the artwork shows in the Source Select like my pic, and then also in the player...if so we nailed it.

**Comment by djdirty60** [comment]
Clearlogo doesn't work again, and now nowhere.  Can't see it anywhere... can that be true?
